### ISSUE TITLE
[collector] Should be possible to use HPA when deploy mode is "statefulset"

### ISSUE THREAD

**Issue by zehenrique** [open-telemetry/opentelemetry-helm-charts#1005]
Currently, when otel collector is deployed as a "statefulset" the charts do not allow using HPA for autoscaling. 
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/hpa.yaml#L1

It should be possible to use HPA when in "statefulset" mode, always having in consideration when and how to scale stateful collectors https://opentelemetry.io/docs/collector/scaling/#scaling-stateful-collectors

**Comment by TylerHelmuth** [comment]
I agree that HPA can be made usable with Statefulset.

**Comment by zehenrique** [comment]
tks. I'll open a PR

**Comment by husnialhamdani** [comment]
@TylerHelmuth 
Can we re-use the existing [hpa.yaml file](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/hpa.yaml) and enable that HPA when the mode is Deployment/Statefulset?

**Comment by TylerHelmuth** [comment]
@husnialhamdani yes

**Comment by lindeskar** [comment]
This is great!
Thanks for implementing the change. I will render and apply the HPA from main while waiting for the next release.

BTW, maybe this comment should be updated?
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/694104bf98cbfdd771d7b72d56a30e1708da80bf/charts/opentelemetry-collector/values.yaml#L489
