### ISSUE TITLE
Remove logging exporter references

### ISSUE THREAD

**Issue by liustanley** [open-telemetry/opentelemetry-helm-charts#1040]
This PR was merged recently which removed the logging exporter from the list of valid exporters: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30408. This results in the following errors when using the helm chart:
```
* error decoding 'exporters': unknown type: "logging" for id: "logging" (valid values: [logzio loki pulsar awsxray dataset googlemanagedprometheus sumologic awskinesis carbon coralogix dynatrace elasticsearch googlecloudpubsub logicmonitor prometheus awsemf skywalking splunk_hec sapm clickhouse opencensus opensearch signalfx awscloudwatchlogs otlp alibabacloud_logservice cassandra file influxdb sentry debug datadog googlecloud kafka mezmo awss3 azuremonitor instana prometheusremotewrite syslog tencentcloud_logservice zipkin alertmanager azuredataexplorer honeycombmarker loadbalancing otlphttp])
2024/02/16 19:25:03 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'exporters': unknown type: "logging" for id: "logging" (valid values: [logzio loki pulsar awsxray dataset googlemanagedprometheus sumologic awskinesis carbon coralogix dynatrace elasticsearch googlecloudpubsub logicmonitor prometheus awsemf skywalking splunk_hec sapm clickhouse opencensus opensearch signalfx awscloudwatchlogs otlp alibabacloud_logservice cassandra file influxdb sentry debug datadog googlecloud kafka mezmo awss3 azuremonitor instana prometheusremotewrite syslog tencentcloud_logservice zipkin alertmanager azuredataexplorer honeycombmarker loadbalancing otlphttp])
```

We should revert the changes made in this PR in order to remove references to the logging exporter: https://github.com/open-telemetry/opentelemetry-helm-charts/pull/907

**Comment by TylerHelmuth** [comment]
@liustanley I believe you'll only run into this issue if you use the image created from `make docker-otelcontribcol` from the contrib repo.  The images published at https://github.com/open-telemetry/opentelemetry-collector-releases still contain the logging exporter

**Comment by TylerHelmuth** [comment]
I was imagining we'd keep the logging export in the helm chart until it is officially removed.

**Comment by liustanley** [comment]
@TylerHelmuth We're using a fork of opentelemetry-collector-contrib with these helm charts, so this broke our CI workflows when we updated our fork with upstream.

**Comment by TylerHelmuth** [comment]
I think this config will remove it from the confmap:

```
config:
  exporters:
    logging: null
```

**Comment by liustanley** [comment]
Thanks! That seems to work
