### ISSUE TITLE
Multi Exporters Configuration For Opentelemetry Collector.

### ISSUE THREAD

**Issue by DevProJSSV** [open-telemetry/opentelemetry-helm-charts#1045]
Hello  Community,

I have a doubt regarding the multi exporter configuration that we should consider when creating pipelines to export logs to different backends or at least different indexes as is my case.

I am using :
apiVersion: v2
name: opentelemetry-collector
version: 0.77.0
appVersion: 0.91.0

from the values.yaml file I am trying to do:

```
pipelines:
      logs:
        exporters:
          - debug
          - splunk_hec/platform_logs
        processors:
          - memory_limiter
          - batch
          - resource/add_agent_k8s
          - resource
          - resourcedetection
        receivers:
          - otlp
      logs/audit:
        exporters:
          - debug
          - splunk_hec/platform_audit_logs
        processors:
          - memory_limiter
          - batch
          - resource/add_agent_k8s
          - resource
          - resourcedetection
        receivers:
          - otlp
      metrics: # Review
        exporters:
          - debug
          - splunk_hec/platform_metrics
        processors:
          - memory_limiter
          - batch
          - resource/add_agent_k8s
          - resource
          - resourcedetection
        receivers:
          - otlp
          - prometheus
      metrics/audit: # Review
        exporters:
          - debug
          - splunk_hec/platform_audit_metrics
        processors:
          - memory_limiter
          - batch
          - resource/add_agent_k8s
          - resource
          - resourcedetection
        receivers:
          - otlp
          - prometheus
      traces:
        exporters:
          - debug
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - jaeger
          - zipkin
```

My exporter section looks like this :

```
config:
  exporters:
    debug: {}
    # Will be removed in a future release.
    # Use the debug exporter instead.
    logging: {}
    splunk_hec/platform_logs:
      endpoint: ""
      token: ""
      index: ""
      source: kubernetes
      tls:
        insecure_skip_verify: true
    splunk_hec/platform_audit_logs:
      endpoint: ""
      token: ""
      index: ""
      source: kubernetes
      tls:
        insecure_skip_verify: true
    splunk_hec/platform_metrics:
      endpoint: ""
      token: ""
      index: ""
      source: kubernetes  
      tls:
        insecure_skip_verify: true 
    splunk_hec/platform_audit_metrics:
      endpoint: ""
      token: ""
      index: ""
      source: kubernetes  
      tls:
        insecure_skip_verify: true 
```

When testing It is working but only for the first pipeline defined as "logs" not the "logs/audit". I tried to change the name of the first pipeline "logs" to "logs/main" and after this, I executed helm template src/k8s/charts/opentelemetry-collector -f src/k8s/charts/opentelemetry-collector/values.yaml to validate the manifest was created without any conflict. Then I noticed that an error regarding the type appears: 

    pipelines:
      logs/main:  # ---------------> I just changed this to "logs/main" from "logs"
        exporters:
          - debug
          - splunk_hec/platform_logs
        processors:
          - memory_limiter
          - batch
          - resource/add_agent_k8s
          - resource
          - resourcedetection
        receivers:
          - otlp
      logs/audit:
        exporters:
          - debug
          - splunk_hec/platform_audit_logs
        processors:
          - memory_limiter
          - batch
          - resource/add_agent_k8s
          - resource
          - resourcedetection
        receivers:
          - otlp
      metrics: # Review
        exporters:
          - debug
          - splunk_hec/platform_metrics
        processors:
          - memory_limiter
          - batch
          - resource/add_agent_k8s
          - resource
          - resourcedetection
        receivers:
          - otlp
          - prometheus
      metrics/audit: # Review
        exporters:
          - debug
          - splunk_hec/platform_audit_metrics
        processors:
          - memory_limiter
          - batch
          - resource/add_agent_k8s
          - resource
          - resourcedetection
        receivers:
          - otlp
          - prometheus
      traces:
        exporters:
          - debug
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - jaeger
          - zipkin

![image](https://github.com/open-telemetry/opentelemetry-helm-charts/assets/160624800/235698a8-9d81-44ae-b366-3afc6663d3b6)

So this makes me think the naming convention might not be interpreted by the chart/collector and due to this just the "logs" pipeline is working. But then how should I name other pipelines for the same type as I am trying to accomplish here? My goal is to have two logs pipelines each one with a different exporter, at least pointing to a different index as you can see in the configuration for Splunk. 

Thank you in advance for any help with this.

@TylerHelmuth

**Comment by TylerHelmuth** [comment]
The `logsCollection` preset requires a pipeline named `logs` to be present in the config.  It will only inject the filelogreceiver into this pipeline.  If you'd like the filelogreceiver in other pipelines you must explicitly add it to the receiver list.

**Comment by DevProJSSV** [comment]
Thank you so much @TylerHelmuth  this was the solution.
