### ISSUE TITLE
Specifying `unavailable_component: null` should not return error

### ISSUE THREAD

**Issue by yaohongkok** [open-telemetry/opentelemetry-helm-charts#1052]
**Describe the bug**
I built a custom collector without the `jaeger` receiver.

I have this Collector config:

```
receivers:
  jaeger: null
  otlp:
    protocols:
      http:

exporters:
  debug:
    verbosity: basic
    sampling_initial: 100
    sampling_thereafter: 1

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug]
```

Note that under receiver, I specify `jaeger: null`. I am doing this because I am trying to override OpenTelemetry Collector official Helm Chart values.yml for my custom Collector.

When run the collector, I get:

```
$ ./otel-collector --config=bug-test.yml

Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'receivers': unknown type: "jaeger" for id: "jaeger" (valid values: [otlp])
2024/02/23 15:50:56 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'receivers': unknown type: "jaeger" for id: "jaeger" (valid values: [otlp])
```

**Steps to reproduce**
1. Create custom Collector
2. Run collector: `./otel-collector --config=bug-test.yml`

Use the above config.

**What did you expect to see?**
Expect to be able to run the Collector withut any issue.

**What did you see instead?**
An error.

**What version did you use?**

v0.90.1

**What config did you use?**

bug-test.yml:
```
receivers:
  jaeger: null
  otlp:
    protocols:
      http:

exporters:
  debug:
    verbosity: basic
    sampling_initial: 100
    sampling_thereafter: 1

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug]
```

**Environment**

Mac OS 

**Additional context**

**Comment by yaohongkok** [comment]
> ```yaml
> traces:
>       receivers: [otlp, zipkin]
> ```

But my configuration does not have any traces. The configuration I shared is the full configuration that I am using to this test issue. 

I don't think the issue is with the chart. It is more likely to be related to the collector.

**Comment by TylerHelmuth** [comment]
Oh if you're not using the helm chart, then the problem is just `jaeger: null`. You can't do that.  That "null" syntax is a helm thing that tells helm to remove a section of the default values.yaml.
