### ISSUE TITLE
Adding extra operators to filelog receiver

### ISSUE THREAD

**Issue by swbsf** [open-telemetry/opentelemetry-helm-charts#1072]
Hello,
I'm trying to add some extra `recombine` configuration to the filelog receiver (such as grouping java traces into a single log block). But I don't see a way of doing this when using your presets, which I want to keep and avoid maintaining.
I was wondering if you'd consider a small patch to allow appending new operators to the filelog receiver? I was thinking of something like 
_in values.yaml_ :
```yaml
presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
    extraFileLogOperators: []
```
_in config.tpl_ :
```diff
diff --git a/charts/opentelemetry-collector/templates/_config.tpl b/charts/opentelemetry-collector/templates/_config.tpl
index 7488e9e..80254b0 100644
--- a/charts/opentelemetry-collector/templates/_config.tpl
+++ b/charts/opentelemetry-collector/templates/_config.tpl
@@ -276,6 +276,9 @@ receivers:
       - type: move
         from: attributes.uid
         to: resource["k8s.pod.uid"]
+     {{- if $.Values.presets.logsCollection.extraFileLogOperators -}}
+     {{ toYaml $.Values.presets.logsCollection.extraFileLogOperators | nindent 6 -}}
+     {{- end }}
       # Clean up log body
       - type: move
         from: attributes.log
```

**Comment by TylerHelmuth** [comment]
We have no plans to add extensibility directly to the preset configuration interface. Our current stance is that the presets should be extremely simple, only allowing enabling/disabling to handle configuring very opinionated configuration. We very much want to avoid configuring the componet via the presets interface.

If you want to extend the preset's configuration you can use `.Values.config.receivers.filelog.operators`, but remember that lists are not merged in Helm so you'd need to include all the operators the preset is configuring.

**Comment by swbsf** [comment]
Yep, I wanted to avoid that precisely. Anyway, i understand your point, thanks taking some time replying.
