### ISSUE TITLE
Opentelemetry Operator - Allow to install as subchart

### ISSUE THREAD

**Issue by PhilippWitzmann** [open-telemetry/opentelemetry-helm-charts#1089]
Hi, 
when trying to deploy this chart as a subchart, helm automatically injects the global: key into values (to share values across multiple subcharts), which is not allowed as per the values.schema.json (see https://github.com/helm/helm/issues/10392 for more information) .

Is it possible, to allow global as a key in values?

**Comment by TylerHelmuth** [comment]
@PhilippWitzmann yes we should add that `global` and `enabled`.
