### ISSUE TITLE
presets.kubernetesAttributes with role and rolebinding

### ISSUE THREAD

**Issue by Marty1703** [open-telemetry/opentelemetry-helm-charts#1099]
Since version 0.97 of the otel-collector-contrib it is possible to use the k8sattributes processor without cluster wide permissions, only a single namespace. 

This functionality has been added with: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31673
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14742

All documentation can be found here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor#namespace-scoped-rbac

I would love to have this functionality build in within the helm chart using the presets.kubernetesAttributes

Some possible options to include would be:

    presets:
      kubernetesAttributes:
        filter: 
	      namespace: <WORKLOAD_NAMESPACE>
or

    presets:
      kubernetesAttributes:
        namespaceScoped: true (default false)

**Comment by TylerHelmuth** [comment]
I'm glad this feature exists, but I'm not sure it should be incorporated into the preset.  We don't like to configure components via the preset and it is a simpler opinionated solution to give the collector access to all namespaces.
