### ISSUE TITLE
Release opentelemetry-collector Helm chart for latest app version (0.42.0)

### ISSUE THREAD

**Issue by j-land** [open-telemetry/opentelemetry-helm-charts#110]
As of writing, the latest opentelemetry-collector (0.8.1) chart supports appVersion 0.37.1. Attempts to use this Helm chart version with an the image for the app version 0.42.0 produces this error in the pod:

`Error: failed to start container "opentelemetry-collector": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/otelcontribcol": stat /otelcontribcol: no such file or directory: unknown`

**Comment by j-land** [comment]
Looking into this further, the issue with pod startup seems to be that there is a discrepancy between the Dockerfile in code (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.42.0/cmd/otelcontribcol/Dockerfile#L14) and the Dockerfile tied to the image in Dockerhub (https://hub.docker.com/layers/otel/opentelemetry-collector-contrib/0.42.0/images/sha256-ec8c214a835edfec73d43340d9099f064973f5273fd5e45b328eaa2beca39115?context=explore) - note the slight difference in entrypoints.

**Comment by dyhack** [comment]
Yes,I got the same prolbem。Using helm,  
`Warning  Failed     12s (x2 over 14s)  kubelet           
Error: failed to start container "opentelemetry-collector": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/otelcontribcol": stat /otelcontribcol: no such file or directory: unknown
`
the image version 0.42.0(otel/opentelemetry-collector-contrib:0.42.0)

**Comment by paulgrav** [comment]
It’s because the entrypoint in the container has been changed from `/otelcontribcol` to `/otelcol-contrib`. Additionally, `--metrics-addr` is no longer a valid argument.

We can override the entrypoint by changing `command.name` in `values.yaml` but the `metrics-addr` arg is hardcoded.
