### ISSUE TITLE
Impossibility to set up `ephemeral-storage` value in the opentelemetry-collector values.yaml

### ISSUE THREAD

**Issue by skyzy06** [open-telemetry/opentelemetry-helm-charts#1104]
Due to some constraints on our platforms, we need to define explicitly the `ephemeral-storage` request and limit for our deployment.
This is a stable feature of k8s since v1.25: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage
However `helm lint` is raising an error when we tried to add the property:
```
14:28:28  [ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
14:28:28  opentelemetry-collector:
14:28:28  - resources.limits: Additional property ephemeral-storage is not allowed
14:28:28  - resources.requests: Additional property ephemeral-storage is not allowed
```
It's due to the fact that [values.schema.json](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.schema.json) is blocking any additional property.

The solution to this issue is to add the support of this property in the chart under the `limits` and `requests` properties:
```json
"ephemeral-storage": {
  "type": "string"
}
```

I have already a pull request about this change if you need a better idea of the change: [Add support of ephemeral-storage in the resources](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1103/files). My issue is only with the collector but I propagated the change to the operator and eBPF as well.

**Comment by TylerHelmuth** [comment]
@skyzy06 this makes sense.  Please open a PR for the opentelemetry-collector. If the feature is needed in other charts we can add that later.

**Comment by skyzy06** [comment]
Hello @TylerHelmuth, thank you for your feedback, I updated my PR to edit only the opentelemetry-collector.

**Comment by ifalex** [comment]
Hello,
We encountered this also in opentelemetry-operator.manager. Was working on older versions of the chart `0.44.2` for example.

**Comment by ifalex** [comment]
@TylerHelmuth how would you like to proceed in this situation? Would you like me to create a new PR for the other one needing it? Or we update the current one to support also the others as initially done by @skyzy06 . Helm lint will fail for all the components in place unfortunately.

**Comment by TylerHelmuth** [comment]
We like changes to a chart in their own PR. Please open a new PR for the operator.
