### ISSUE TITLE
[FileLogReceiver] `.Values.namespaceOverride` instead of `.Release.Namespace` should be used to "exclude" Otel-collector log

### ISSUE THREAD

**Issue by yingsamsung** [open-telemetry/opentelemetry-helm-charts#1108]
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/0d569572313bbbde68a09db945e9bbbfde16a582/charts/opentelemetry-collector/templates/_config.tpl#L196

Problem:
When `overrideNamespace` is different from `Release.Namespace`, Otel-collector log is not excluded properly.

Repro:
1. install OpenTelemetry-Collector chart with `namespaceOverride: monitoring`, without specify `--namespace` on `helm install`. Note that, open-telemetry-agent pod is installed in `monitoring` namespace in K8S cluster. 
2. check logs under `/var/log/pods`. The folder of collector log is actually `monitoring_opentelemetry-collector-agent-....`, while in ConfigMap,

```
Data
====
relay:
----
receivers:
  filelog:
    exclude:
    - /var/log/pods/default_obv-opentelemetry-collector*_*/opentelemetry-collector/*.log
```
Note that, the `default` release namespace is used, which causes log from Otel collector is still being collected.

**Comment by TylerHelmuth** [comment]
@yingsamsung nice find, would you like to submit a PR?
