### ISSUE TITLE
Opentelemetry Gateway Configuration

### ISSUE THREAD

**Issue by reidlai** [open-telemetry/opentelemetry-helm-charts#112]
According to Opentelemetry documentation, we can implement gateway deployment other than collector.  But I cannot find any implementation details in these chart settings or from documentation.  Any hint to let me know how to configure opentelemetry gaetway for large cluster?  Thanks

**Comment by TylerHelmuth** [comment]
If you want a gateway deployment of the collector then I think the [standaloneCollector](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector#default-configuration) settings are what you want.  The standalone collector is a single deployment of the collector within the Cluster.  

Typically the agent (daemonset) deployment of the collector is used in tangent with the standalone collector and the helm charts support this.  If you enable both the agent and standalone collector then the agents will be configured to export their data to the standalone deployment of the collector.
