### ISSUE TITLE
additionalProperties helm lint failure when using opentelemetry-operator as subchart

### ISSUE THREAD

**Issue by ifalex** [open-telemetry/opentelemetry-helm-charts#1133]
During this issue https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1065 additionalProperties was set to False for opentelemetry-operator creating a disruptive behavior for helm lint in the situation of using opentelemetry-operator as a subchart.

As the current consensus from helm community based on the long discussed issue https://github.com/helm/helm/issues/10392 is to discuss this matters with chart originator I'd like to present the scenario when the operator is consumed as a subchart by a customer.
In our scenario we created under the umbrella chart a set of templates that ease end-user usability of the chart including the otel-operator.
For example created a template for collectors that allow configuration only from values.yaml.
Therefore in our values.schema.json under the umbrella chart we will have under opentelemetry-operator this field called collectors (but could be anything else like there was a scenario sometime ago with enabled flag).

Using the chart as a subchart is a pretty common scenario therefore I would suggest reverting the additionalProperties to its previous value (default to True).
I can open a PR if allowed.

**Comment by TylerHelmuth** [comment]
@ifalex is there a specific property you're adding to the subchart that is causing a failure?

**Comment by ifalex** [comment]
Hi @TylerHelmuth, as specified in initial message we use opentelemetry-operator inside an umbrella chart. In order to ease the utilization process by our developers we created a collector dictionary in values.yaml which does a wrapping of OpenTelemetryCollector CR and can be modified by client directly from values.yaml.

Is another pattern to consume OpenTelemetryCollector that we found to be quite useful for our clients. More on that in an argocd setup this will mean only configuration without any need to create CRs.

On top of helm lint issue failing in our pipelines, also argocd uses a helm lint mechanism which is also causing failure due to the missing property, as additionalProperties is set on False.

By not leaving additionalProperties set to True we enforce against typos which consumer should detect on their own, limiting scenarios of usability for opentelemetry-operator as a subchart for example.

Even if we add `collector:` as an object to the parent `values.schema.json` this will not prevent other additions to fail in the future.
My proposal in this case would be to rever to the additionalProperties: True that the values.schema.json had until a few months ago.

**Comment by TylerHelmuth** [comment]
@ifalex does your values.yaml file look like:

```
# top level chart details
...
opentelemetry-operator:
  collectors:
    # custom section nested under opentelemetry-operator
    ...
  # Other operator options
  ...
```

We also use `additionalProperties: false` in the collector and demo chart to help users write their values.yaml, but also to help with field deprecations (see https://github.com/open-telemetry/opentelemetry-helm-charts/issues/91).

Although the OTel Operator manages the OpenTelemetryCollector Custom Resource, the opentelemetry-operator does not. Is their a strict requirement that the `collectors` section be nested under `opentelemetry-operator`?

**Comment by ifalex** [comment]
@TylerHelmuth Indeed, will manage it on our side. Thanks for the nice explanation! We can close the issue.
