### ISSUE TITLE
Impossibility to set up ephemeral-storage value in the opentelemetry-operator values.yaml

### ISSUE THREAD

**Issue by ifalex** [open-telemetry/opentelemetry-helm-charts#1134]
Raising this ticket as a follow up to the discussion to add ehpemeral-storage to opentelemetry-operator's values.schema.json from https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1104
Will create a PR accordingly.

**Comment by jdiegosierra** [comment]
@ifalex any update? I can create the PR if you don't have time

**Comment by ifalex** [comment]
@jdiegosierra If you can, please do so, can't accommodate it based on my day to day tasks right now, unfortunately.
