### ISSUE TITLE
[opentelemetry-collector] Allow to configure startup probe

### ISSUE THREAD

**Issue by ElfoLiNk** [open-telemetry/opentelemetry-helm-charts#1152]
Due to compaction on startup when using a persisted queue with file storage, the liveness probe then terminates the collector, causing it to enter a CrashLoopBackoff state in this scenario.

Allowing the setup of a proper startup probe will prevent the need for significant changes to the liveness probe or its disabling.

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32456

**Comment by lindeskar** [comment]
Created #1351 to add `startupProbe` to the collector Pods.
