### ISSUE TITLE
OpenTelemetry Collector Helm Installation- Pod with ImagePullErr

### ISSUE THREAD

**Issue by banandh** [open-telemetry/opentelemetry-helm-charts#1159]
Hi- Im trying helm in my minikube , able to run the operator but having pod image pull issues with open telemetry collector.

**Helm Install**
helm install my-opentelemetry-collector open-telemetry/opentelemetry-collector --set mode=deployment --set image.repository="otel/opentelemetry-collector-k8s" --set command.name="otelcol-k8s"
NAME: my-opentelemetry-collector
LAST DEPLOYED: Fri Apr 26 18:43:30 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
[WARNING] No resource limits or requests were set. Consider setter resource requests and limits for your collector(s) via the `resources` field.

[WARNING] "useGOMEMLIMIT" is enabled but memory limits have not been supplied, which means no GOMEMLIMIT env var was configured but the Memory Ballast Extension was removed. It is highly recommended to only use "useGOMEMLIMIT" when memory limits have been set.

**kubectl get pods**
NAME                                          READY   STATUS         RESTARTS       AGE
opentelemetry-operator-748b475cb9-zrdnl       2/2     Running        20 (16d ago)   34d
demo-collector-588ff6b9f5-5gvg2               1/1     Running        0              21s
**my-opentelemetry-collector-5ccb4b57cd-mpbq5   0/1     ErrImagePull   0              17s**
 

Pod describe 
 Warning  Failed     7m46s (x4 over 9m55s)  kubelet            Failed to pull image "otel/opentelemetry-collector-k8s:0.96.0": Error response from daemon: manifest for otel/opentelemetry-collector-k8s:0.96.0 not found: manifest unknown: manifest unknown
  Warning  Failed     7m46s (x4 over 9m55s)  kubelet            Error: ErrImagePull
  Warning  Failed     7m35s (x6 over 9m55s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    8s (x36 over 9m55s)    kubelet            Back-off pulling image "otel/opentelemetry-collector-k8s:0.96.0"

Is this image available? Do i need to run with any different values.yaml?

**Comment by TylerHelmuth** [comment]
@banandh the first tag for the `otel/opentelemetry-collector-k8s` is `0.98.0`.  What version of the chart are you using?

**Comment by banandh** [comment]
@TylerHelmuth  - Chart version opentelemetry-collector-0.85.0

helm list       
NAME                      	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                         	APP VERSION
my-opentelemetry-collector	default  	1       	2024-04-26 18:43:30.181275 +0530 IST	deployed	opentelemetry-collector-0.85.0	0.96.0     
opentelemetry-operator    	default  	1       	2024-03-22 20:02:41.823097 +0530 IST	deployed	opentelemetry-operator-0.51.2 	0.96.0

**Comment by TylerHelmuth** [comment]
The default collector version for chart 0.85.0 is `v0.96.0`.  The image that you set, `image.repository="otel/opentelemetry-collector-k8s"` does not have a `v0.96.0` tag.

You should either update your chart version, explicitly set the image tag, or use a different image.

**Comment by banandh** [comment]
i updated chart to opentelemetry-collector-0.90.1 version. In the helm install its expecting image repo.

Should I use otel/opentelemetry-collector-k8s or otel/opentelemetry-collector-contrib:0.99.0. Not sure if both are same.

helm install my-opentelemetry-collector open-telemetry/opentelemetry-collector --set mode=<value> --set image.repository="otel/opentelemetry-collector-k8s" --set command.name="otelcol-k8s"

**Comment by banandh** [comment]
OpenTelemetry collector is started.

Used helm install my-opentelemetry-collector open-telemetry/opentelemetry-collector --set mode=deployment --set image.repository="otel/opentelemetry-collector-k8s" --set command.name="otelcol-k8s"

**Comment by banandh** [comment]
Collector  was in running state for sometime and then I keep seeing it 0/1 running status. Liveness probe failed: Get "http://10.42.0.97:13133/": dial tcp 10.42.0.97:13133: connect: connection refused. 

Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  46m                   default-scheduler  Successfully assigned default/my-opentelemetry-collector-7744ff5458-k5f4n to lima-rancher-desktop
  Normal   Killing    46m                   kubelet            Container opentelemetry-collector failed liveness probe, will be restarted
  Normal   Pulled     45m (x2 over 46m)     kubelet            Container image "otel/opentelemetry-collector-k8s:0.99.0" already present on machine
  Normal   Created    45m (x2 over 46m)     kubelet            Created container opentelemetry-collector
  Normal   Started    45m (x2 over 46m)     kubelet            Started container opentelemetry-collector
  Warning  Unhealthy  45m (x4 over 46m)     kubelet            Liveness probe failed: Get "http://10.42.0.97:13133/": dial tcp 10.42.0.97:13133: connect: connection refused
  Warning  BackOff    11m (x88 over 40m)    kubelet            Back-off restarting failed container opentelemetry-collector in pod my-opentelemetry-collector-7744ff5458-k5f4n_default(347bf258-cdff-422c-8f80-68020de42049)
  Warning  Unhealthy  100s (x124 over 46m)  kubelet            Readiness probe failed: Get "http://10.42.0.97:13133/": dial tcp 10.42.0.97:13133: connect: connection refused
banandh@MCHICL652W60 ~ % helm install my-opentelemetry-collector open-telemetry/opentelemetry-collector --set mode=deployment --set image.repository="otel/opentelemetry-collector-k8s" --set command.name="otelcol-
