### ISSUE TITLE
Reference Grafana Dashboard 

### ISSUE THREAD

**Issue by adussarps** [open-telemetry/opentelemetry-helm-charts#1174]
Hello,

I've been searching but haven't come across any reference or base Grafana dashboards that effectively utilize the Kubernetes metrics generated with this Helm chart. It would greatly assist in finalizing a quick setup of the collectors/agents.

Best regards.

**Comment by TylerHelmuth** [comment]
@adussarps checkout the opentelemetry-demo chart in this repo, there is a dashboard in their for the Collector.

**Comment by adussarps** [comment]
Thanks I'll do this
