### ISSUE TITLE
[collector] Use `container` parser in the filelogreceiver

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-helm-charts#1188]
Stanza has a new [container parser](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/container.md).  We should see if our logsCollection preset can use it to simplify the configuration we generate for users.

**Comment by TylerHelmuth** [comment]
@ChrsMark do you have interest it taking up this issue?

**Comment by ChrsMark** [comment]
Sure! Feel free to assign it to me.
