### ISSUE TITLE
Issue on creating opentelemetry-collector

### ISSUE THREAD

**Issue by ionelialupu** [open-telemetry/opentelemetry-helm-charts#1190]
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/2f4e7a8f960366b961d621c9bc7c6ae389129af3/charts/opentelemetry-kube-stack/templates/collector.yaml#L24

The following error is returned:
Error: template: opentelemetry-kube-stack/templates/collector.yaml:24:8: executing "opentelemetry-kube-stack/templates/collector.yaml" at <include "opentelemetry-collector.config" $merged>: error calling include: template: no template "opentelemetry-collector.config" associated with template "gotpl"

**Comment by ionelialupu** [comment]
It should be "opentelemetry-kube-stack.config"

**Comment by TylerHelmuth** [comment]
/cc @jaronoff97.

@ionelialupu I think technically that chart is still under initial development.  Your experience right now will vary.

**Comment by ionelialupu** [comment]
Thanks for the feedback. I will look forward for the new updates.

**Comment by jaronoff97** [comment]
yep under development, this will be fixed in #1166
