### ISSUE TITLE
[collector] No collector reload when using external configmap

### ISSUE THREAD

**Issue by boxidau** [open-telemetry/opentelemetry-helm-charts#1194]
Hello 👋 we're using the collector chart with an external config. This is being done in order to utilize templating for the config since the collector chart is invoked as a sub-chart. 

When specifying an externally managed ConfigMap to use as config for a collector, it would be great if the deployment checksum annotation could use a helm lookup function to read in the externally referenced configmap and generate a sha.

This way the deployment will rollout restart on deployment of a new config. In our specific case the externally managed config map is managed by the parent chart so will also cause a re-render of the deployment (and thus lookup) during helm upgrade.

**Comment by JaredTan95** [comment]
it can be closed as it fixed by https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1302?
