### ISSUE TITLE
Not possible to create ServiceMonitor if running in DaemonSet mode

### ISSUE THREAD

**Issue by tiithansen** [open-telemetry/opentelemetry-helm-charts#1212]
It should be possible to monitor collectors if they run in DaemonSet mode.

https://github.com/open-telemetry/opentelemetry-helm-charts/blob/ad613643be0db1a18cc9bf8ccd0fd22a9b734f89/charts/opentelemetry-collector/templates/servicemonitor.yaml#L1 condition won't allow to create ServiceMonitor if in DaemonSet mode.

**Comment by TylerHelmuth** [comment]
This is a hold-over from when we didn't allow the daemonset mode to create a service.  Now that we allow daemonset to have a service, we should allow the service monitor as well.
