### ISSUE TITLE
Enable setting duration and renew before values for cert manager Certificate resource in Operator chart

### ISSUE THREAD

**Issue by wmfowlkes** [open-telemetry/opentelemetry-helm-charts#1227]
We are forced to take the aws pca issuer duration default value for our eks certificates since the Operator helm chart does not allow us to set the duration and renew before values for our cert manager Certificate.  See [certmanager.yaml](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/templates/certmanager.yaml)
Hoping for an update to the chart to allow setting the values directly on the Certificate.

**Comment by jaronoff97** [comment]
@wmfowlkes thanks for opening this, makes a ton of sense for this to be customizable. I just opened a PR :)

**Comment by wmfowlkes** [comment]
@TylerHelmuth Thanks!!
