### ISSUE TITLE
Make opentelemetry-operator tests to not fail once new operator version is released

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-helm-charts#126]
opentelemetry-operator helm chart tests was written in a way that the validation is happening against the latest version of the operator. It breaks the opentelemetry-operator helm chart tests every time a new version of the operator is released.

For example, currently this PR is blocked https://github.com/open-telemetry/opentelemetry-helm-charts/pull/125

**Comment by dmitryax** [comment]
Hey @open-telemetry/operator-approvers, can anyone please help with this issue?

**Comment by jpkrohling** [comment]
As an operator approver myself, I don't have the required knowledge to help here. If no other operator maintainer/approver is able or willing to help here, and no other people are found among the original helm chart contributors, I suggest deprecating the chart.

**Comment by pavolloffay** [comment]
I would suggest pinning the operator version and fix the tests when the operator version is updated.

**Comment by TylerHelmuth** [comment]
I can take a shot at this
