### ISSUE TITLE
[collector] Cannot deploy on Kubernetes 1.20 because of `internalTrafficPolicy` using helm charts from artifact hub

### ISSUE THREAD

**Issue by Uncle-Justice** [open-telemetry/opentelemetry-helm-charts#1269]
same as https://github.com/grafana/alloy/issues/1212, i faced this problem: 

```
[wanshanpeng@*** opentelemetry-collector]$ helm  --kubeconfig=/root/.kube/yao_config   install pws-test ./ --set image.repository="otel/opentelemetry-collector-k8s" --set mode="deployment"   -n test
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/yao_config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/yao_config
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Service.spec): unknown field "internalTrafficPolicy" in io.k8s.api.core.v1.ServiceSpec
```

Then i had to delete`internalTrafficPolicy` in values to avoid this, then everything went fine

my k8s version is 1.20, i got this helm chart by `helm pull open-telemetry/opentelemetry-collector`

**Comment by Uncle-Justice** [comment]
@dosu, you r right, and we can also make the steps automatical by adding a decision logic that determines behavior based on the k8s version.

**Comment by TylerHelmuth** [comment]
@Uncle-Justice this helm chart [supports k8s 1.24+](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector#prerequisites). While dosubot's second suggestion is correct, we don't plan to start supporting less than 1.24.
