### ISSUE TITLE
Need code owners for opentemetry-operator helm chart

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-helm-charts#127]
The operator helm chart need more attention.

@open-telemetry/operator-maintainers please let us know who can help with maintaining it and can be added as a code owner.

**Comment by jpkrohling** [comment]
I don't think any of the current Operator maintainers did anything regarding the helm chart for it.

**Comment by alolita** [comment]
@erichsueh3 from AWS has also been working on the operator helm chart. He can help maintain the releases for the helm chart to stay current with the Collector versions.

**Comment by VineethReddy02** [comment]
@dmitryax I can be part of maintaining otel-operator helm chart :)

**Comment by erichsueh3** [comment]
@dmitryax @alolita I can also help out!

**Comment by dmitryax** [comment]
Thanks @VineethReddy02 and @erichsueh3. I think we currently have at least couple of issues related to the operator:
- https://github.com/open-telemetry/opentelemetry-helm-charts/issues/132
- https://github.com/open-telemetry/opentelemetry-helm-charts/issues/69
and this one that would be very useful for both charts:
- https://github.com/open-telemetry/opentelemetry-helm-charts/issues/78

Feel free to take any of them

**Comment by dmitryax** [comment]
Another issue reported https://github.com/open-telemetry/opentelemetry-helm-charts/issues/145

**Comment by TylerHelmuth** [comment]
@jaronoff97 and @abelperezok would you be interested in taking a more active role in the operator chart?

**Comment by TylerHelmuth** [comment]
closing as @Allex1 is now code owner.
