### ISSUE TITLE
[collector] Memory limiter processor cannot be disabled

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-helm-charts#1272]
The collector's Helm Chart allows disabling any configuration's component by setting it to null, for example:

```yaml
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
```

In addition, custom pipelines that don't use these components must also be provided. This is particularly useful when using the Helm Chart with a collector distribution that does not embed some of the default chart components.

The same concept cannot be applied to the `memory_limiter` processor because it is always added by the `chart` when not defined by the user, see template:

```
{{- define "opentelemetry-collector.baseConfig" -}}
{{- $processorsConfig := get .Values.config "processors" }}
{{- if not $processorsConfig.memory_limiter }}
{{-   $_ := set $processorsConfig "memory_limiter" (include "opentelemetry-collector.memoryLimiter" . | fromYaml) }}
{{- end }}
```

Is the `memory_limiter` component a requirement for this chart? What do you think of adding a new value to parametrize it like the `.Values.useGOMEMLIMIT` but for the memory_limiter? (e.g `.Values.useK8SMEMLIMIT`)

**Comment by TylerHelmuth** [comment]
Although it is a best practice, the chart shouldn't be requiring it since the collector can run fine without it (unlike who we must have the health_check extension).

I'd be ok with updating the template to not add it back if it is not present.  I don't think we need any other fields to control it. Would you like to submit that fix?

**Comment by rogercoll** [comment]
> I'd be ok with updating the template to not add it back if it is not present. I don't think we need any other fields to control it. Would you like to submit that fix?

:+1: Definitely, preparing the fix
