### ISSUE TITLE
Endpoint on opampbridge should support tls cert

### ISSUE THREAD

**Issue by 3-commerce** [open-telemetry/opentelemetry-helm-charts#1279]
I attemp to try opampbridge [on this values](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-kube-stack/values.yaml#L751)

It's asking the endpoint of opamp server. However, based on opamp-go Agent [in this repository](https://github.com/open-telemetry/opamp-go/blob/ed38d5f4bf930b57e04581919fbfb676aaa5a5af/internal/examples/agent/agent/agent.go#L97) we have to determine the CA tls for connecting to opamp server.

Is this Endpoint opamp server is http or wss (protobuf) ? In the example, it's given http but i am not sure the communication between agent to server using http. It should be websocket.

I don't find the opamp-server image, but i try to build it localy.

**Comment by 3-commerce** [comment]
Hi @jaronoff97 

I have succeded to connect bridge endpoint to amp server (VM).
I choose amp server (VM) because it's provided the UI. However when i try "Save and Send to Agent", it's not work (the otelcol config is not reflected as i want and some configs part are removed when displayed.
 
<img width="310" alt="Screenshot 2024-07-26 at 23 02 26" src="https://github.com/user-attachments/assets/0735a011-2475-4262-9770-fac998b6d3f2">

**Comment by jaronoff97** [comment]
I believe this is a bug in the latest opamp-bridge server. I have seen this reported elsewhere. Would you mind opening a new issue in the [operator repo](https://github.com/open-telemetry/opentelemetry-operator) for this, and I can take a look there?

**Comment by jaronoff97** [comment]
while there, can you also provide a link to the opamp server implementation please?

**Comment by 3-commerce** [comment]
@jaronoff97 Hi, i really happy and glad to cooperate with you. meanwhile I cannot much contribute in code but I hope can help you for testing. 😅

How do i contact you in private ? Have a slack or something ?

**Comment by jaronoff97** [comment]
no problem! You can message in the #agentmanwg in the CNCF slack and we can follow up there. Closing this issue for now.
