### ISSUE TITLE
Helm Chart Installation Does Not Create Any Resources in Kubernetes Cluster

### ISSUE THREAD

**Issue by gustavosett** [open-telemetry/opentelemetry-helm-charts#1281]
**Environment:**
- **Helm Version:** `Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"`
- **Kubernetes Version:** `Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2`
- **Operating System:** Windows 11
- **Shell:** PowerShell

**Issue Description:**
I am attempting to install the `opentelemetry-kube-stack` Helm chart in my Kubernetes cluster under the `monitoring` namespace using the following command:

```
helm install opentelemetry-kube-stack open-telemetry/opentelemetry-kube-stack --namespace monitoring --create-namespace --set opentelemetry-operator.admissionWebhooks.certManager.enabled=false --set opentelemetry-operator.admissionWebhooks.autoGenerateCert.enabled=true
```

The Helm installation completes and reports that it has been successfully deployed. However, when I check for resources in the `monitoring` namespace using:

```
kubectl get all -n monitoring
```

It returns "No resources found in monitoring namespace."

**Expected Behavior:**
Resources such as Deployments, Services, and other Kubernetes components specified in the Helm chart should be created in the `monitoring` namespace.

**Actual Behavior:**
No resources are created in the namespace, and no errors are displayed during the Helm chart installation process. This occurs despite the Helm release showing as successfully deployed.

**Troubleshooting Steps Tried:**
1. Uninstalling and reinstalling the chart.
2. Checking Helm release status and history which shows the chart as deployed.
3. Looking at the manifest using `helm get manifest opentelemetry-kube-stack -n monitoring` which shows all resources defined correctly but they do not materialize in the cluster.

![image](https://github.com/user-attachments/assets/5a1c0c5d-c373-49fa-90ef-f0f8a11a2137)

**Comment by gustavosett** [comment]
there was missing my values.yaml configuration.

**Comment by djpirra** [comment]
What you mean it was missing?
