### ISSUE TITLE
[opentelemetry-kube-stack] Chart testing doesn't work when the operator is enabled.

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-helm-charts#1300]
We saw some issues in https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1299 where:

1. the name was too long
2. a race condition when pods where in `CreatingContainer` and seen as failed instead of waiting longer.

**Comment by jaronoff97** [comment]
@TylerHelmuth I'll look into this first thing Monday. OOC why was this causing a race for chart testing? Is the uninstall / cleanup failing?

**Comment by TylerHelmuth** [comment]
From local runs it looked like it didn't like waiting for the collectors to start once the operator had started.
