### ISSUE TITLE
Resource/Span attributes collision possible due to default K8s processor behavior

### ISSUE THREAD

**Issue by bixu** [open-telemetry/opentelemetry-helm-charts#1311]
The behavior of [this](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/96fc70a2e8a05b300e25d7d544fcb723a8db23be/charts/opentelemetry-collector/values.yaml#L52-L53) default can have surprising unwanted consequences.

Example:

- A team adds the `name` label to a k8s Pod
- Backends that don't differentiate between Resource and Span attributes can display traces such that each span shows the k8s pod `name` as the name of the span

Proposal:

Consider some namespacing when this default is enabled. For example, `k8s.pod.label.<label value>`.

**Comment by TylerHelmuth** [comment]
@bixu the [semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/k8s.md#pod) do specify a namespacing.  This feature was added before that and we are not going to update it until the k8s semantic conventions are stabilized, to minimize the amount to times we need to do a breaking change.

If you need some namespacing I suggest not using the `.Values.preset.kubernetesAttributes.extractAllPodLabels` field and instead configure the extraction manually:

```yaml
  k8sattributes:
    extract:
      labels:
        - tag_name: k8s.pod.label.$$1
          key_regex: (.*)
          from: pod
```

**Comment by bixu** [comment]
Thanks for the context, we're fine with explicitly configuring this until the semconv settles.
