### ISSUE TITLE
[HELM] [OPENTELEMETRY COLLECTOR] deltatocumulative processor is not recognized by  otel/opentelemetry-collector-contrib:0.107.0 docker image 

### ISSUE THREAD

**Issue by Masmiiadm** [open-telemetry/opentelemetry-helm-charts#1313]
## Issue Summary

An error occurs when attempting to retrieve the configuration, specifically when decoding the 'processors'. The error indicates that an unknown type "deltatocumulative" was provided, which is not recognized as a valid value.

## Error Details
failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):
error decoding 'processors': unknown type: "deltatocumulative" for id: "deltatocumulative" (valid values: [memory_limiter groupbytrace remotetap k8sattributes resource span transform batch deltatorate groupbyattrs logdedup experimental_metricsgeneration metricstransform tail_sampling sumologic attributes cumulativetodelta filter probabilistic_sampler redaction resourcedetection routing])

**Comment by TylerHelmuth** [comment]
@Masmiiadm The deltatocumulative processor has not yet been added to the [contrib distribution](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml).  It was [mark alpha today](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34747), so it should be added in the 0.108.0 release of the contrib distro
