### ISSUE TITLE
Introduce values schema for the collector chart

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-helm-charts#135]
Introduce [values.schema.json](https://helm.sh/docs/topics/charts/#schema-files) for values.yaml input validation in opentelemetry-collector helm chart. All the objects in values.yaml with predefined set of properties should not allow unknown properties.

This is a preliminary step for any big change to the helm chart configuration, e.g. https://github.com/open-telemetry/opentelemetry-helm-charts/issues/91

The following schema can be used as a reference: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/values.schema.json

**Comment by TylerHelmuth** [comment]
I can look at this.

**Comment by TylerHelmuth** [comment]
There is a lot of schema to add.  Will probably submit PRs in  small chunks to make review easier since each bit of validation added is valid in itself.

**Comment by dmitryax** [comment]
> There is a lot of schema to add. Will probably submit PRs in small chunks to make review easier since each bit of validation added is valid in itself.

Sounds good. Thanks!
