### ISSUE TITLE
Provide OCI Artifact helm chart release #260

### ISSUE THREAD

**Issue by shuai-hao-hs** [open-telemetry/opentelemetry-helm-charts#1350]
We are using ECR pull through cache to get external helm charts.

It would be nice to have a OCI Artifact release for the helm charts.

It could be provided via Docker Hub, GitHub Continer Registry, or any other OCI Artifact compatible registry that AWS ECR supports.

```
Amazon ECR currently supports creating pull through cache rules for the following upstream registries.

Docker Hub, Microsoft Azure Container Registry, GitHub Container Registry, and GitLab Container Registry (Requires authentication)

Amazon ECR Public, the Kubernetes container image registry, and Quay (Doesn't require authentication)
```

For example:

```
# ghcr.io
helm install opentelemetry-collector oci://ghcr.io./open-telemetry/opentelemetry-collector-helm-charts
```

See: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by shashankram** [comment]
Is the OCI registry public? What's the path at which it is available?
