### ISSUE TITLE
Introduce values schema for the operator chart

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-helm-charts#136]
Introduce [values.schema.json](https://helm.sh/docs/topics/charts/#schema-files) for values.yaml input validation in opentelemetry-operator helm chart. All the objects in values.yaml with predefined set of properties should not allow unknown properties.

**Comment by TylerHelmuth** [comment]
@Allex1 are you available to work on this?

**Comment by Allex1** [comment]
@TylerHelmuth I can give it a go
