### ISSUE TITLE
Additional property selector is not allowed: opentelemetry-kube-stack-0.2.1

### ISSUE THREAD

**Issue by suresh-target** [open-telemetry/opentelemetry-helm-charts#1360]
I'm trying to add a label selector to kubeScheduler service, but looks like the schema does not support that option, details are as below

**helm chart** - `opentelemetry-kube-stack-0.2.1`

value.yaml config

```
kubeScheduler:
  enabled: true
  service:
    selector:
      k8s-app: kube-scheduler

```
Executed command:-

`helm upgrade --install opentelemetry-kube-stack kubernetes-charts/opentelemetry-kube-stack -f ./prom-value.yaml`

error received

```
\Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-kube-stack:
- kubeScheduler.service: Additional property selector is not allowed

```

**Steps to reproduce:**
Modify the value.yaml file to add `selector` under `kubeScheduler.service` , save the value file and install the chart using helm.

Having this option provide more flexibility to use prometheus configuration, appreciate to have similar configuration in other components such as  etcd, controller, etc.

**Comment by jaronoff97** [comment]
closed by #1370
