### ISSUE TITLE
ServiceMonitor fails to pickup kubernetes services: opentelemetry-kube-stack-0.2.1

### ISSUE THREAD

**Issue by suresh-target** [open-telemetry/opentelemetry-helm-charts#1371]
**Observed Problem:** Following ServiceMonitors fail to pickup kubernetes services  
 
- opentelemetry-kube-stack-kube-etcd
- opentelemetry-kube-stack-kube-scheduler
- opentelemetry-kube-stack-kube-controller-manager
 

 The above mentioned ServiceMonitors are looking for the services that are matching two labels, ` app: opentelemetry-kube-stack-$exporter ` and `release: $.Release.Name`. 
 For example the ServiceMonitor of `kube-controller-manager`  is looking for the services that are having following labels

 ```
app: opentelemetry-kube-stack-kube-controller-manager
release: opentelemetry-kube-stack

```
But the label `release: opentelemetry-kube-stack` is missing from service hence the lookup fails.

**Steps to reproduce:** 

1. Modify the value.yaml file to modify the `kubeControllerManager.enabled` or `kubeEtcd.enabled` or `kubeScheduler.enabled` 
to true , save the values file and install the chart using helm
2.  Run the command `kubectl get svc -l release=opentelemetry-kube-stack`  to confirm that none of the services are listing related to above mentioned components
OR
Curl against the jobs endpoint to confirm that none of the target links are listing related to any of the above mentioned components.

example command: `curl http://opentelemetry-kube-stack-daemon-targetallocator.kube-system.svc.cluster.local/jobs`

**Comment by jaronoff97** [comment]
I'll give this a try to reproduce. Thank you for reporting!

**Comment by suresh-target** [comment]
Thanks a lot @jaronoff97 ,Looks like this is already fixed through this [PR](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1363)

**Comment by jaronoff97** [comment]
@suresh-target great! can i close this then?

**Comment by jaronoff97** [comment]
thanks for reporting it! :bow:
