### ISSUE TITLE
Align Major and Minor Versions Between version and appVersion in Chart.yaml files

### ISSUE THREAD

**Issue by jvoravong** [open-telemetry/opentelemetry-helm-charts#1378]
Description:

In the current Chart.yaml setup, the version (chart version) and appVersion (version of the app deployed by the chart) have major and minor versions that are not always in sync. This inconsistency makes it difficult to track the chart version and the appVersion that were deployed together. From my experience, this is unusual. I would like to request the version and appVersion major and minor version partss always match, allowing for easier version tracking and debugging.

I propose that we ensure the major and minor versions of both version and appVersion in Chart.yaml are always kept in sync, while allowing the patch version to increment independently for any differences between them. 

This would:
- Improve clarity by making it easier to associate the chart version with the app version it deploys.
- Make debugging and maintenance more straightforward, as users can easily match versions across projects.
- The patch version can continue to increment independently as changes are made, but keeping major and minor versions aligned will provide a more consistent and predictable experience for users of the charts.
- You can see in Chart.yaml files the major and minor versions do not match between `version` and `appVersion`.
  - https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/Chart.yaml
  - https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/Chart.yaml
  - https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-ebpf/Chart.yaml
  - https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-kube-stack/Chart.yaml
  - https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/Chart.yaml

Operator Chart.yaml Example:
- [Currently has `version: 0.71.0` and `appVersion: 0.110.0`](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/3a6fff3f065dafcdcf7041885c5d0d1bf61a1167/charts/opentelemetry-operator/Chart.yaml#L3C1-L3C16)
- Desired output of this ticket would be `version: 0.110.0` and `appVersion: 0.110.0` or more abstractly `version: 0.110.X` and `appVersion: 0.110.X` in the Chart.yaml.

**Comment by TylerHelmuth** [comment]
This is an interesting idea, but we currently don't do this by design. It allows us to release the chart independently from the thing it deploys and follow its own semvar standard. Sometimes there are breaking changes or features in the chart that are based on Kubernetes and not the thing being installed. 

Keeping the major and minor in lock step with the app version is also not a pattern I've seen in other charts. The Prometheus charts, which we like to follow when we can, does not do this suggestion for example. Have you seen other charts do this?

**Comment by jvoravong** [comment]
@TylerHelmuth thanks for the feedback. I see the value in releasing the chart independently to handle chart-level breaking changes. I’ve seen some vendor distributions especially for the collector align chart and app (major, minor) versions to simplify tracking and maintenance.

Why:
- It improves clarity, making it easier to associate chart and app versions. Which can make debugging easier.
- Independent patch increments could still handle chart-specific changes while keeping major/minor versions aligned for predictability. 

I understand this request would requires more discipline, ensuring breaking changes align with major or minor updates. While this approach might not fit all charts, I believe it would reduce overhead for core ones like the collector and operator charts since OpenTelemetry has a strong versioning definition defined. Other charts, such as the kube-stack, could still follow independent versioning as needed.

This is more of a nice-to-have. I’ll leave the request open for two more weeks to gather feedback and will close it if there’s no further interest.
