### ISSUE TITLE
[collector] PrometheusRule is not created when using PodMonitor

### ISSUE THREAD

**Issue by lindeskar** [open-telemetry/opentelemetry-helm-charts#1379]
The condition here:

https://github.com/open-telemetry/opentelemetry-helm-charts/blob/3a6fff3f065dafcdcf7041885c5d0d1bf61a1167/charts/opentelemetry-collector/templates/prometheusrule.yaml#L1

means the PrometheusRule resource is not created when using PodMonitor instead of ServiceMonitor (makes sense for `mode: daemonset`).

Can change the condition to check for both values?

**Comment by crutonjohn** [comment]
didn't see the contribfest label on this one, but i'm working on this anyways :)
