### ISSUE TITLE
[chore] Bump kube-rbac-proxy image

### ISSUE THREAD

**Issue by vasireddy99** [open-telemetry/opentelemetry-helm-charts#1394]
Bump [kube-rbac-proxy image in operator](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/b8406fc3f5814a26556e8267182f3fd5d36d7d83/charts/opentelemetry-operator/values.yaml#L191-L195) to the recent released version - [v0.18.1](https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.18.1).

**Comment by jaronoff97** [comment]
closed by #1397
