### ISSUE TITLE
Add more comprehensive CI scenarios

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-helm-charts#140]
Currently we validate only standalone collector mode with default configuration https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/ci/standalone-collector-values.yaml

We need more test cases to cover as many configuration options as possible

**Comment by dmitryax** [comment]
@TylerHelmuth can you take this one as well?

**Comment by TylerHelmuth** [comment]
> @TylerHelmuth can you take this one as well?

I'm going to be on PTO all next week, but I can look at it when I'm back if no one else has grabbed it.

**Comment by dmitryax** [comment]
Sounds good!

**Comment by TylerHelmuth** [comment]
@dmitryax I think it could be nice to test PodMonitor and ServiceMonitor, but they require the Prometheus operator to exist on the cluster.  I we could update the kind cluster creation to also install the operator, but do you think there is good ROI on the time spent to do that?

**Comment by dmitryax** [comment]
> @dmitryax I think it could be nice to test PodMonitor and ServiceMonitor, but they require the Prometheus operator to exist on the cluster. We could update the kind cluster creation to also install the operator, but do you think there is good ROI on the time spent to do that?

I'm pretty sure it's not. I don't expect it to be that important part of the chart.

**Comment by TylerHelmuth** [comment]
> I'm pretty sure it's not. I don't expect it to be that important part of the chart.

I figured the same. Submitted the PR without it.
