### ISSUE TITLE
support OCI helm charts

### ISSUE THREAD

**Issue by M0NsTeRRR** [open-telemetry/opentelemetry-helm-charts#1429]

**Comment by TylerHelmuth** [comment]
@M0NsTeRRR please add details to this issue.

**Comment by M0NsTeRRR** [comment]
I've added the link in the PR that fix the issue, but it would be cool if otel helm chart support OCI registries as highlighted in helm documentation https://helm.sh/docs/topics/registries/.

**Comment by M0NsTeRRR** [comment]
> @M0NsTeRRR can you check if the prometheus charts support this

yes they used ghcr.io as you can see [here](https://github.com/orgs/prometheus-community/packages?repo_name=helm-charts)
and the github action is here https://github.com/prometheus-community/helm-charts/blob/main/.github/workflows/release.yaml#L53
