### ISSUE TITLE
Feature Request: Helm Chart for Target Allocator

### ISSUE THREAD

**Issue by nicolastakashi** [open-telemetry/opentelemetry-helm-charts#1447]
## Description  
The Target Allocator (TA) is a sub-project of the OpenTelemetry Operator. While it is commonly used alongside the Operator, it is also capable of running as a standalone application without requiring the Operator. 

To enhance user adoption and simplify deployment, I propose creating a Helm chart for the Target Allocator. This would allow users to easily deploy TA in Kubernetes environments without the need for the OpenTelemetry Operator.

---

## Motivation  
- **Ease of Deployment:** A Helm chart will streamline the deployment process for users who prefer not to rely on the OpenTelemetry Operator.  
- **Wider Adoption:** By providing a standalone Helm chart, more users can integrate TA into their Kubernetes workflows.  
- **Flexibility:** Users can deploy TA independently or as part of a custom setup that does not include the Operator.  

---

## Proposed Solution  
- Develop a Helm chart for the Target Allocator with:
  - Configurable parameters (e.g., replicas, resource requests/limits, environment variables).
  - Support for popular configurations such as custom service discovery.
  - Optionally, integrate with existing observability stacks, e.g., Prometheus and OpenTelemetry.

---

## Expected Outcome  
- Users will be able to deploy the Target Allocator using a single Helm command:  
  ```bash
  helm install target-allocator <chart-repo>

**Comment by jaronoff97** [comment]
@nicolastakashi this is a duplicate issue with https://github.com/open-telemetry/opentelemetry-helm-charts/issues/334... TL;DR I tried to make this work but it was reallyyyyy hard to get helm to do the replacement that the operator does to convert the prometheus config given for the TA... if we were to limit the scope of the chart to deploy a TA with its own jobs that it communicates to the collector that would be okay, otherwise this is challenging...

**Comment by TylerHelmuth** [comment]
Closing in favor of https://github.com/open-telemetry/opentelemetry-helm-charts/issues/334, @nicolastakashi feel free to keep the conversation going in that issue.

**Comment by nicolastakashi** [comment]
My idea was only about deploy TA and not configure prometheus receiver @jaronoff97
