### ISSUE TITLE
Add support for provisioning the operator

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-helm-charts#16]
I just noticed this repository and thought it would be a good idea to suggest that this repository could also provide a chart to provision the [OpenTelemetry Operator](https://github.com/open-telemetry/opentelemetry-operator/), in a similar way that the [Jaeger Helm Chart](https://github.com/jaegertracing/helm-charts/) provisions the Jaeger Operator.

**Comment by kuzaxak** [comment]
I think that issue can be closed
