### ISSUE TITLE
Add ability to install collector as a StatefulSet

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-helm-charts#177]
The opentelemetry-collector chart should have an option to be installed as a StatefulSet.  This will allow us to better support certain configurations, such as agents sending data via the loadbalancing exporter.

**Comment by sherifkayad** [comment]
Some notes from the duplicate ticket:
- These certain configurations include the Persistent Queues feature of the exporters or the File Storage extension to prevent "circumstantial" data loss whenever there's a problem with the backend and at the same time, the Collector restarts.
- The Helm chart should:
  - Allow defining persistence specs for the `StatefulSet` (e.g. the storage class, the storage request size, .. etc.)
  - Allow defining the `PodManagementPolicy` of the `StatefulSet` => could be `Parallel` by default as there's no need to guarantee the order of startup of multiple Collector pods
