### ISSUE TITLE
Extract chart specific jobs from lint-test.yaml

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-helm-charts#179]
Currently https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/.github/workflows/lint-test.yaml has steps related to one chart or another, and conditions are not always correct. We should consider extracting those steps into other jobs.

**Comment by TylerHelmuth** [comment]
Are you thinking a workflow for the operator chart and a workflow for collector chart or even more granular than that?

**Comment by dmitryax** [comment]
I'm thinking of one extra workflow for each of the charts and keeping common tests in the same workflow
