### ISSUE TITLE
Ability to add a PrometheusRule

### ISSUE THREAD

**Issue by ben-natan** [open-telemetry/opentelemetry-helm-charts#203]
It would be nice being able to add a PrometheusRule for prometheus alerting. 

The pipeline I'm working on uses Grafana Tempo which already supports this in its [tempo-distributed chart](https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed); adding such a feature to the opentelemetry-collector chart would allow seamless integration of Prometheus alerting for the whole pipeline.

**Comment by ben-natan** [comment]
Ongoing PR: https://github.com/open-telemetry/opentelemetry-helm-charts/pull/202

**Comment by TylerHelmuth** [comment]
I don't think PrometheusRule is a native k8s object, what is defining it?  Is it the Prometheus Operator?

**Comment by ben-natan** [comment]
It is a Prometheus CRD, just like PodMonitor and ServiceMonitor already present in this chart.
