### ISSUE TITLE
Default filelog receiver config causes failure

### ISSUE THREAD

**Issue by lamebear** [open-telemetry/opentelemetry-helm-charts#204]
When running with the default `filelog` receiver config, the following error is thrown when attempting to process log entries:

```
Failed to process entry	{"kind": "receiver", "name": "filelog", "operator_id": "move5", "operator_type": "move", "error": "move: field does not exist", ...
```

That error corresponds to this operator:
```
- from: attributes.run_id
  to: attributes["run_id"]
  type: move
```

Can this be removed?

**Comment by lamebear** [comment]
Had to recreate the PR to change the commit user.

**Comment by dmitryax** [comment]
I believe the error is thrown because we are trying to move it from the same place. I think we should just rename it to the name defined in semantic conventions Currently, this change doesn't remove it from attribute

**Comment by TylerHelmuth** [comment]
The [contrib's example ](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/kubernetes/otel-collector-config.yml) doesn't have that stanza for `run_id`.  I didn't experience any errors with the charts running in GCE, but maybe `run_id` is not ok in other environments?
