### ISSUE TITLE
Set `k8s.container.restart_count` attribute instead of run_id in filelog receiver

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-helm-charts#207]
`k8s.container.restart_count` defined in the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/k8s.md#container) should be used instead of `run_id`.

**Comment by lamebear** [comment]
`k8s.container.restart_count` is already included in the generated config:

https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/_config.tpl#L191-L193

**Comment by dmitryax** [comment]
Oh my bad. Didn't notice that. Thanks for pointing me to it
