### ISSUE TITLE
Can't send metrics to otel collector

### ISSUE THREAD

**Issue by MicahDevOps** [open-telemetry/opentelemetry-helm-charts#211]
Can anyone help me look into this issue? My applications seem failing to send metrics to otel collector.
I have done some research on Google but turn out not helpful to solve the problem since those articles are talking about workloads running on local host with docker-compose

1.My applications (Pods) is running with [open telemetry java agent ](https://github.com/open-telemetry/opentelemetry-java) and configured with the following environment variants
OTEL_EXPORTER_OTLP_ENDPOINT: http:///otel-opentelemetry-collector:4317
OTEL_METRICS_EXPORTER:        otlp

tracing info can be sent to otel and works just fine.But i can't see any metrics info.

2. my configuration of otel collector (default port 8888 for metrics is enabled)
2.1  Use the default configuration (no modification in exporters,processors, receivers and pipeline)
When i tried to pull metrics from otel in prometheus, I can just see metrics of otel collector itself ! No metrics from my applications
    - job_name: otel
      static_configs:
      - targets:
        - otel-opentelemetry-collector:8888

2.2 Add prometheus exporters
In my limited understanding, my applications send telemtry data (trace,metrics) to OTEL_EXPORTER_OTLP_ENDPOINT
And otel collector receivers just support "otlp" so i don't need a customized receiver, right ?
Thus, I add a prometheus exporter
 exporters:
     prometheus: prometheus:9090
     namespace: default
...
 pipelines:
    metrics:
          exporters: [logging,prometheus]
          processors: [memory_limiter,batch]
          receivers: [otlp]

However,either checking from prometheus or http://otel-opentelemetry-collector:8888/metrics, still can't see the metrics generated by my application.

Can anyone help to give a glue ? Why my application failed to send log to otel collector ? 
And if i want to check what metrics did the opentelemetry javaagent collect,how to do that ?
Thanks !!!

**Comment by TylerHelmuth** [comment]
Hello @MicahDevOps.

The collector's localhost:8888/metrics endpoint is how it exposes is own metrics; you'll never see data it is processing at that endpoint.

Instead, for the logging exporter, set the `loglevel` to `debug`, and you'll see the data the collector is processing in all the pipeline's for which the logging exporter is added.

You are correct that if java is exporting on OTLP then the standard OTLP receiver will work.  If you switch the logging exporter to debug do you see data in the collector's logs?

**Comment by MicahDevOps** [comment]
> Hello @MicahDevOps.
> 
> The collector's localhost:8888/metrics endpoint is how it exposes is own metrics; you'll never see data it is processing at that endpoint.
> 
> Instead, for the logging exporter, set the `loglevel` to `debug`, and you'll see the data the collector is processing in all the pipeline's for which the logging exporter is added.
> 
> You are correct that if java is exporting on OTLP then the standard OTLP receiver will work. If you switch the logging exporter to debug do you see data in the collector's logs?

Thanks for your guide. After setting loglevel to 'debug', i can see metrics from my application displaying in collector's logs.
But, how can i visualize the metrics ? 

I am using Grafana Loki as the log driver ,Grafana Tempo as tracing backend and prometheus for metrics.
How can i show the metrics (now showing in collector's log) to backend ,like prometheus ?

And BTW,Yes, i am installing the otel collector using helm chart

**Comment by MicahDevOps** [comment]
Hello @TylerHelmuth 
I am using the helm chart.
After setting the loglevel to debug, i can verify that metrics from my applications exactly display in collector's logs.
And i add a prometheus exporter like

exporters:
   prometheus: 0.0.0.0:8889
   namespace: default


From my Prometheus side, i can pull my application metrics  from host "otel-collector:8889"

However, i still have a question. The values.yaml within helm chart only have 8888 port available for metric.
are there any ways for users to add their preferred ports ?

**Comment by TylerHelmuth** [comment]
Great! Can this issue be closed?

**Comment by MicahDevOps** [comment]
yes, please. And thanks again
