### ISSUE TITLE
Allow using custom ports for metrics, health checks and proxy

### ISSUE THREAD

**Issue by abelperezok** [open-telemetry/opentelemetry-helm-charts#214]
This is very helpful when using in combination with `hostNetwork:true` especially if you have several other add-ons already in the cluster where they also chose the same ports, an example of that is using Calico CNI on EKS. 

An example where this is already done is AWS Load Balancer Controller, https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/main/helm/aws-load-balancer-controller

Ideally, it should provide parameters to the chart looking something like these:
```
--set metricsBindPort=9444 
--set livenessBindPort=8087 
--set readinessBindPort=8089 
--set proxyBindPort=8444
```

**Comment by TylerHelmuth** [comment]
That seems like a good feature add.  Is it something you want to contribute @abelperezok?

**Comment by abelperezok** [comment]
@TylerHelmuth Yes, I could do that, I've done something similar on the DAPR project for the same reason. https://github.com/dapr/dapr/pull/4181

**Comment by TylerHelmuth** [comment]
Sweet I'll assign this issue to you.

**Comment by abelperezok** [comment]
@TylerHelmuth I'm preparing a PR for this issue, while at it I found that the webhook port was hardcoded inside the manager, so I opened another issue and submitted a PR in the operator repo for that. 

In order for my proposed changes in the helm chart to work, the new CLI flag will need to be already in place in the corresponding container image.

**Comment by TylerHelmuth** [comment]
Are you planning to contribute this to the opentelemetry-collector chart, opentelemetry-operator charts, or both?

**Comment by abelperezok** [comment]
@TylerHelmuth if my understanding is correct, this is feature is limited to the operator (chart and code). Do you think there are changes also required in the collector ?

**Comment by abelperezok** [comment]
The changes in operator code are in this PR (https://github.com/open-telemetry/opentelemetry-operator/pull/899) awaiting review

**Comment by TylerHelmuth** [comment]
Conceptually the collector chart could have its readiness and liveliness ports configurable, although the use cases would be minimal. Doing it only for the operator chart is probably the best.

**Comment by abelperezok** [comment]
@TylerHelmuth the PR has been submitted now, with regards chart versioning, what do you advise ?

**Comment by TylerHelmuth** [comment]
If there is nothing breaking previous versions then bumping only the patch number is good.

**Comment by abelperezok** [comment]
Well, to get the full benefit from this update, it depends on the next version of the operator to be published, the current version (v0.51.0) doesn't have the extra CLI flags available. 
Not sure if that justifies a bump in minor version.

**Comment by TylerHelmuth** [comment]
Bumping the operator version does require bumping the chart's minor version. It should also be done in its own PR.

**Comment by abelperezok** [comment]
Thanks, in that case, I'll put this on hold until the operator updates are published, then I'll bump the version and complete the chart update. Does it sound good to you ?

**Comment by TylerHelmuth** [comment]
Sounds good

**Comment by abelperezok** [comment]
@TylerHelmuth the PR https://github.com/open-telemetry/opentelemetry-operator/pull/899 was merged and therefore issue https://github.com/open-telemetry/opentelemetry-operator/issues/896 was closed. 
I reckon those changes will available with the next release.

**Comment by abelperezok** [comment]
@TylerHelmuth There has been a new release of the operator https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.52.0 which includes my changes. 

Which change should I submit first ? 
- bumping the operator version to v0.52.0 and chart version to 0.8.0 
- updating the chart to use the new cli flags

**Comment by TylerHelmuth** [comment]
Everyone seems eager for 0.52.0 haha there are already 2 other people who have submitted PRs for https://github.com/open-telemetry/opentelemetry-helm-charts/issues/227.  I'd say the new cli flags since others are doing the version bump.
