### ISSUE TITLE
Posibility to use daemonset along with the service.

### ISSUE THREAD

**Issue by theodrim** [open-telemetry/opentelemetry-helm-charts#217]
Hello. I was wondering is it possible to have mode set to `daemonset` and have service available at the same time?
I'm asking about opentelemetry-collector helm chart.

**Comment by TylerHelmuth** [comment]
The charts do not currently support a service with mode=daemonset. What use case did you have in mind?

**Comment by theodrim** [comment]
@TylerHelmuth replacing `node-exporter` but since our cluster using spot instances - it would be reasonable to use daemonset to assume that every new node gets `opentelemetry-collector` deployed.
Unless I'm missing something and metrics still can be scraped even without the service?

**Comment by TylerHelmuth** [comment]
> Unless I'm missing something and metrics still can be scraped even without the service?

I might have interpreted this question incorrectly. Are you referring to scraping the collectors metrics on itself 
 (0.0.0.0:8888/metrics) ?

**Comment by theodrim** [comment]
> Are you referring to scraping the collectors metrics on itself
(0.0.0.0:8888/metrics) ?

Probably. I've initially though that it is possible to have only agent exposing metrics by itself (as having `mode: deployment` and service enabled giving desired results) but now realizing that collector might be required to have external scraping done by prometheus at first and vmagent later.

Is my understanding correct, that having `opentelemetry-agent` with `mode: daemonset` and `opentelemetry-collector` with enabled prometheus receiver as well as pipeline will get desired results?

**Comment by TylerHelmuth** [comment]
I think it would be possible for a deployment instance of the collector to scrape the telemetry of the agent instances, but the current charts set up the collector to scrape itself: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml. When deployed as a daemonset (or a deployment) the default config for the chart is to have the collector scrape its own metrics, which could then be exported anywhere and anyway you want.

**Comment by kostya9** [comment]
I have another use case which could benefit from service for daemonset.

Imagine that apps could be both in a k8s cluster and not (e.g. in the process of migrating or for some other reason some apps are outside of the cluster). As a developer, I want to send tracing data from inside and outside of the cluster to the collectors.

**Comment by TylerHelmuth** [comment]
> As a developer, I want to send tracing data from inside and outside of the cluster to the collectors.

In this scenario running a deployment instance of the collector in addition to a daemonset seems like the correct approach. Applications inside k8s would send traces to the daemonset (and the daemonset would forward to the deployment if necessary). Applications outside the collector would send directly to the deployment.

**Comment by TylerHelmuth** [comment]
Handled via https://github.com/open-telemetry/opentelemetry-helm-charts/pull/427
