### ISSUE TITLE
Helm Chart for the Operator Collector CRDs

### ISSUE THREAD

**Issue by lorelei-rupp-imprivata** [open-telemetry/opentelemetry-helm-charts#220]
We use the helm chart to roll out the operator, but are making our own helm chart to roll out the operator's CRDs for the collector
Is there any plans to have a helm chart that goes with the operator to roll out the operator CRDs for the collectors?

**Comment by Allex1** [comment]
@lorelei-rupp-imprivata you probably mean the collector CR (custom resource) and not CRD (which needs to be deployed in the cluster in order for the operator to work)

**Comment by lorelei-rupp-imprivata** [comment]
> @lorelei-rupp-imprivata you probably mean the collector CR (custom resource) and not CRD (which needs to be deployed in the cluster in order for the operator to work). I think #69 is related

Yes thats exactly my issue! I think we can close this as a duplicate
