### ISSUE TITLE
Update open-telemetry charts to reflect change in crd collector spec

### ISSUE THREAD

**Issue by moh-osman3** [open-telemetry/opentelemetry-helm-charts#296]
Trying to run an HPA with a statefulset collector and got the following error when trying to specify a `minReplica` value

```
% helm upgrade lightstep ./collector_k8s -f ./collector_k8s/values.yaml -f ./collector_k8s/values-remote.yaml -n opentelemetry --install --create-namespace
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(OpenTelemetryCollector.spec): unknown field "minReplicas" in io.opentelemetry.v1alpha1.OpenTelemetryCollector.spec
```

and then looked at https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml#L177 and it seems that `minReplicas` is actually missing

Can this be updated to reflect this https://github.com/open-telemetry/opentelemetry-operator/commit/0232b80b1885bf616d4cc5134c6422ed51f7199b? Thanks!

**Comment by TylerHelmuth** [comment]
@Allex1 did the bump to 0.56.0 fix this issue?

**Comment by Allex1** [comment]
@TylerHelmuth the `minReplica` field is present in the new CRD but I haven't tested . 
Maybe @moh-osman3 can give it a go ?

**Comment by moh-osman3** [comment]
I applied the udpated CRD to my collector statefulset and confirmed that `minReplica` is now recognized and works as expected. Thanks for the help!
