### ISSUE TITLE
Add Target Allocator/Stateful Set Option

### ISSUE THREAD

**Issue by blakeromano** [open-telemetry/opentelemetry-helm-charts#310]
The CRD for the collector allows for the creation of the target allocator for prometheus which uses some of the data from the config on the collector regarding prometheus. However the Helm Chart has not added that support as well. This should be done to add awareness and adoption of the Target Allocator especially since lots of work on the Prometheus/Opentelemetry work has been going on

**Comment by Allex1** [comment]
@blakeromano thanks for the heads up. 
In the current operator chart we don't create/manage any custom resources (like the OpentelemetryCollector), we just provide some examples in the readme in order for the user to create and manage his own collector/s 
Can you clarify what is the expectation  regarding the targetAllocator resource?

**Comment by TylerHelmuth** [comment]
@blakeromano is this issue related: https://github.com/open-telemetry/opentelemetry-helm-charts/issues/69

**Comment by blakeromano** [comment]
Related yes. I think there is a benefit to having a helm chart that would do both the operator and collector without the usage of the CRD.
