### ISSUE TITLE
[opentelemetry-demo] Refactor component env vars to better handle service names

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-helm-charts#340]
Also, I think we should refactor something to make setting env var easier. Adding env vars for specific services that rely on other services (and therefore the Release name) doesn't feel graceful.

I can open an issue for this later.

_Originally posted by @TylerHelmuth in https://github.com/open-telemetry/opentelemetry-helm-charts/pull/337#discussion_r953223476_

**Comment by dineshg13** [comment]
Currently demo application isn't working.  See #358 . When i manually fixed that in my environment , am seeing that checkout service is unable to connect to email service 
```
{"message":"failed to send order confirmation to \"tobias@example.com\": failed POST to email service: Post \"demo-email-service:8080/send_order_confirmation\": unsupported protocol scheme \"demo-email-service\"","severity":"warning","timestamp":"2022-09-09T01:22:19.778637815Z"}
```

**Comment by TylerHelmuth** [comment]
@2start would you like to take point on this issue?

**Comment by 2start** [comment]
#363 describes the issue in more detail.
