### ISSUE TITLE
Add k8s_cluster receiver to presets and/or provide guidance on usage with helm chart

### ISSUE THREAD

**Issue by akats7** [open-telemetry/opentelemetry-helm-charts#350]
Hi all, I have been trying to enable the k8s_cluster receiver and k8s_events receiver on my collector, but have not been able to enable them without crashing my collector. Has anyone had any luck with this/ is there a known reason this wouldn't work.

If this should be possible to enable while consuming the chart, it would be good to potentially see some guidance on this as it doesn't seem to work out of the box, also this seems like a good option to have as a potential preset.

**Comment by TylerHelmuth** [comment]
Hello @akats7.  Feels like there are 2 issues here:
1. Help running [k8sclusterreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver) and [k8seventsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8seventsreceiver)
2. Feature request to add [k8sclusterreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver) and [k8seventsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8seventsreceiver) as presets

For 1, we can try to help, but we need to know more about your setup and the error you are seeing.  Can you provide your values.yaml, the chart version you are using, and the error you are seeing?

For 2, can you open a separate issue specifically requesting a new preset(s)?

**Comment by akats7** [comment]
Hi Tyler, 
Sure thing, I'll open a new issue requesting the additional preset.

In regards to my issue running the receivers, I'm using v0.28.0.

My values.yaml is pretty minimal, I also tried creating a clusterrole and clusterrolebinding for the created service account, using the guidance [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver) 

mode: deployment

ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false

extraEnvs:
  - name: <ENV1>
    valueFrom:
      configMapKeyRef:
        name: env1
        key: env1
  - name: <ENV2>
    valueFrom:
      configMapKeyRef:
        name: env2
        key: env2
 
config:
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
    k8s_cluster:
      collection_interval: 10s
  processors:
    batch: {}
  exporters:
    logging:
      loglevel: debug
    otlp:
      endpoint: <ENDPOINT>
  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [logging, otlp]
      metrics:
        receivers: [otlp, k8s_cluster]
        exporters: [logging,  otlp]
      logs:
        receivers: [otlp]
        exporters: [logging]

and the error I'm getting on collector startup is:
Error: cannot build pipelines: failed to create "k8s_cluster" receiver, in pipeline "metrics": failed to setup the receiver: failed to fetch group version details: Get "https://10.96.x.x:443/apis/v1": read tcp 192.168.x.x:58402->10.96.x.x:443: read: connection reset by peer - error from a previous attempt: read tcp 192.168.x.x:58392->10.96.x.x:443: read: connection reset by peer
2022/09/01 14:45:47 collector server run finished with error: cannot build pipelines: failed to create "k8s_cluster" receiver, in pipeline "metrics": failed to setup the receiver: failed to fetch group version details: Get "https://10.96.x.x:443/apis/batch/v1": read tcp 192.168.x.x:58402->10.96.x.x:443: read: connection reset by peer - error from a previous attempt: read tcp 192.168.x.x:58392->10.96.x.x:443: read: connection reset by peer

**Comment by TylerHelmuth** [comment]
@akats7 please make sure your RBAC is set correctly: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8seventsreceiver#rbac
