### ISSUE TITLE
[opentelemetry-demo] Load generator is unable to connect to frontend service

### ISSUE THREAD

**Issue by dineshg13** [open-telemetry/opentelemetry-helm-charts#358]
When we install demo application on k8s cluster, loadgenerator is unable to connect to frontend. We see error trace in the jaeger as well . 

![image](https://user-images.githubusercontent.com/2471669/189366284-6cef5cef-5110-4eb8-ba49-5dfc23cb1c93.png)

**Comment by TylerHelmuth** [comment]
@dineshg13 do you plan to work on this?
