### ISSUE TITLE
Checkout service can't access email service

### ISSUE THREAD

**Issue by 2start** [open-telemetry/opentelemetry-helm-charts#363]
**Observation**

The following error occurs:

```
failed to send order confirmation to "mark@example.com": failed POST to email service: Post "my-otel-demo-email-service:8080/send_order_confirmation": unsupported protocol scheme "my-otel-demo-email-service"
```

**Explanation**

The checkout service uses the following env var `EMAIL_SERVICE_ADDR: release-name-email-service:8080`.
The env var is used in the code as follows:

```
resp, err := otelhttp.Post(ctx, cs.emailSvcAddr+"/send_order_confirmation", "application/json", bytes.NewBuffer(emailServicePayload))
```

The error occurs because the http:// protocol prefix is missing. However, the `SERVICE_ADDR` emails are automatically generated out of the service dependencies via the following snippet:

```
# {{ $.depends }}
# {{ .name }}
{{- if hasKey $.depends .name }}
{{- range $depend := get $.depends .name }}
- name: {{ printf "%s_ADDR" $depend | snakecase | upper }}
  value: {{ printf "%s-%s:%0.f" $prefix ($depend | kebabcase) (get $.serviceMapping $depend )}}
{{- end }}
{{- end }}
```

It is therefore not straight forward how to change this in an elegant way. The setup feels a little over generified.

**Comment by TylerHelmuth** [comment]
@2start Do you know if the email service's code is breaking a standard that the other services follow by not adding the http prefix? Or is this the only situation where this applies?

**Comment by 2start** [comment]
@TylerHelmuth It took a superficial look earlier. Unlike the other services the email-service is no grpc service. It's a ruby service. I.e. it uses a http library, which requires us to specify http:// or https://. I think there are two possible solutions.

Just touch our repo:

1. Specify the protocol in the address similar to [opentelemetry-demo .env](https://github.com/open-telemetry/opentelemetry-demo/blob/main/.env).

The second solution would be to change the following things in the open-telemetry-demo:

1. Create new env variable for the protocol i.e. EMAIL_SERVICE_ENABLE_HTTPS (default: false)
2. Change go code to consider the new variable.
3. Change address in .env file to remove http:// prefix.

**Comment by 2start** [comment]
Tbh. it would also improve the original setup. 
However, the problem at our side occurs because we bind our generated dependency addresses directly to the go code in the demo itself. We would need an optional layer inbetween to decouple this. Like a "getter" function. 

I propose to write a quick n dirty fix by checking if the address belongs to the email-service. If so I can prefix the addr with http://. If there will be multiple outliers, we can still fix this in a more sophisticated manner.

**Comment by TylerHelmuth** [comment]
> I propose to write a quick n dirty fix by checking if the address belongs to the email-service.

yes we can do this for now to get the chart working for the 1.0 release of the demo.  Do you plan to work on that?

**Comment by 2start** [comment]
sure I can write the fix today
