### ISSUE TITLE
Add support for priorityClassName to otel operator deployment

### ISSUE THREAD

**Issue by geoffreytran** [open-telemetry/opentelemetry-helm-charts#370]
Priority classes are used by k8s to determine which pods to evict in cases where nodes are removed from the cluster or under resource congestion. The operator is a good case where we would want to set the priority class to keep the operator from being evicted and ensure it's the first pods starting so that downstream pods with auto instrumentation sidecars/agents will be instrumented properly.

This was completed for the collector chart, but doesn't currently exist for the operator.

https://github.com/open-telemetry/opentelemetry-helm-charts/pull/49

https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

**Comment by TylerHelmuth** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-helm-charts/pull/433
