### ISSUE TITLE
Add Kubernetes Events preset

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-helm-charts#381]
Hey,

This https://github.com/open-telemetry/opentelemetry-helm-charts/issues/350#issue-1358927903 issue mentioned support for Kubernetes Event as a preset. So I'm creating a seperate issue. What are thoughts around this?

I'm thinking UX would be something like this:
```
presets:
  eventsCollection:
    enabled: false

```

and then configure k8s_event receiver and use the ClusterRole mentioned in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8seventsreceiver#rbac

FYI I can work on this :)

**Comment by TylerHelmuth** [comment]
@povilasv assigned.  Thanks!

**Comment by nicolastakashi** [comment]
@povilasv and @TylerHelmuth now we have k8sobjectreceiver working as expected to collect Kubernetes events, shall we add this as a preset, to collect events?
