### ISSUE TITLE
[demo] - allow image names/tags to be configured

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-helm-charts#406]
Since the OpenTelemetry community demo is meant to be forked/vendored, we want to ensure that a vendor can modify an image of one or more of the service components and leverage the official chart to deploy.

Ideally, we can have a default image name and tag prefix that can be configured for all service components, as well as the ability to override just an individual service component.

**Comment by TylerHelmuth** [comment]
Doing some research in the chart it is possible to set the default image for all services and also overwrite, but the values.yaml doesn't make this clear.  I will clean things up.
