### ISSUE TITLE
Allow user to enable ingress in agent/daemonset mode

### ISSUE THREAD

**Issue by rkosegi** [open-telemetry/opentelemetry-helm-charts#415]
Currently user is restricted to use ingress only when collector is deployed in `deployment` mode and user explicitly enable it.
We have use case where collector is running in agent mode, but at same time it could also ingest trace spans from outside of cluster.
Can this [artificial restriction](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/dcaeddac11897bc9e7c452efced12307665bee84/charts/opentelemetry-collector/templates/ingress.yaml#L1) be removed from chart?

**Comment by TylerHelmuth** [comment]
I'm in favor of allowing the chart to be configured as needed, even if it might not be the most optimal. We have started allowing this more since we moved to presets, such has host metrics and file log in a deployment. It also normally simplifies the chart. 

@dmitryax @Allex1 do you agree?

**Comment by dmitryax** [comment]
I'm good with adding support for that use case

**Comment by dmitryax** [comment]
@rkosegi do you want to submit a PR?

**Comment by rkosegi** [comment]
@dmitryax here is my proposed solution. It's just simplification of current logic. This also allows to expose collector into cluster when running in agent mode.
