### ISSUE TITLE
[DEMO] Recommendation service errors when calling product catalog service

### ISSUE THREAD

**Issue by joshleecreates** [open-telemetry/opentelemetry-helm-charts#436]
Repeated errors in the recommendation service matching the trace screenshot below. It seems to be a problem communicating with product catalog service but I don't have the bandwidth to investigate at the moment. 

I have confirmed that this behavior only occurs with Kubernetes — running the latest version of the demo with docker-compose does not produce this error.

<img width="1468" alt="Screen Shot 2022-10-17 at 12 50 13 PM" src="https://user-images.githubusercontent.com/11478793/196270982-d0a36b7b-16fd-40ed-95bb-1ec03171e4a8.png">

**Comment by puckpuck** [comment]
This seems to be resolved with the latest version of the Helm chart.  Can you re-test this?

**Comment by joshleecreates** [comment]
I'm still seeing this with chat version 0.9.2 but now I see errors in the log for the recommendation service, which I don't think were there before, so... progress? It's possible that this is an issue with my cluster if nobody else is seeing this.

**Comment by TylerHelmuth** [comment]
@joshleecreates whats your setup? I had a pretty annoying day with an M1 pro and Kind.

**Comment by joshleecreates** [comment]
@TylerHelmuth I'm using single-node k3s with containerd, cilium, and metallb on an x86 machine.

**Comment by TylerHelmuth** [comment]
@joshleecreates in that case, when you get a chance, can you test if the featureflag service is starting up successfully.

**Comment by joshleecreates** [comment]
@TylerHelmuth yes in my tests it always succeeds in connecting to postgres after 1-2 restarts.

**Comment by joshleecreates** [comment]
@TylerHelmuth Unfortunately yes. I'll do some digging this week if I have time.

<img width="1470" alt="Screen Shot 2022-11-08 at 9 36 39 AM" src="https://user-images.githubusercontent.com/11478793/200593169-20ff7037-6c4d-4d5e-95fb-1efe01784fae.png">

**Comment by joshleecreates** [comment]
This is no longer occurring for me. Closing.
