### ISSUE TITLE
[demo] - add prometheus and grafana components

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-helm-charts#443]
The OpenTelemetry demo uses Prometheus and Grafana to ingest and visualize metrics. We need to add these to the demo's Helm chart and set the collector's config to export metrics to Prometheus.  We will also require a set of default charts to be deployed to Grafana as part of this.

**Comment by dmitryax** [comment]
Closing as completed in https://github.com/open-telemetry/opentelemetry-helm-charts/pull/456
