### ISSUE TITLE
[operator] Opentelemetry Operator Collector contrib image

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-helm-charts#446]
At the moment we default to regular opentelemetry-collector image in the Operator chart. Lines:

 https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/values.yaml#L20-L22
 
I was thinking maybe instead of this image we should use contrib one? As it has way more receivers / processors / exporters and gives better default user experience.

Also it would be the same as we do for opentelemetry-collector chart -> https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L124-L125

And I believe we use contrib for the opentelemetry-demo too

Thoughts?

**Comment by TylerHelmuth** [comment]
I agree on standardizing on contrib for the charts.  @Allex1 @dmitryax do you agree?

**Comment by dmitryax** [comment]
Makes sense let's use the same image by default across all the charts
