### ISSUE TITLE
operator missing ingress rbac roles

### ISSUE THREAD

**Issue by seankhliao** [open-telemetry/opentelemetry-helm-charts#457]
The latest version of the operator [v0.61.0](https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.61.0) appears to require roles to get/list/watch(?) Ingresses.
Without them it fails to make any progress

> E1020 10:08:01.991330       1 reflector.go:140] pkg/mod/[k8s.io/client-go@v0.25.3/tools/cache/reflector.go:169](http://k8s.io/client-go@v0.25.3/tools/cache/reflector.go:169): Failed to watch *v1.Ingress: failed to list *v1.Ingress: [ingresses.networking.k8s.io](http://ingresses.networking.k8s.io/) is forbidden: User "system:serviceaccount:opentelemetry-operator:opentelemetry-operator-controller-manager" cannot list resource "ingresses" in API group "[networking.k8s.io](http://networking.k8s.io/)" at the cluster scope

**Comment by Allex1** [comment]
@seankhliao, this has been [added](https://github.com/open-telemetry/opentelemetry-helm-charts/commit/5cb4d46e005e68323e9411a94426ca668144b1f2#diff-bd2633cf0804f0badd4644cb029eaad518031ade4cd79143ec943860e9cf11d9R126) in the latest helm version for the operator chart.

**Comment by seankhliao** [comment]
Ahhh, what I get for delaying filing issues for a day.
Thanks!
