### ISSUE TITLE
[opentelemetry-operator] Usage of labels and selector labels

### ISSUE THREAD

**Issue by edwintye** [open-telemetry/opentelemetry-helm-charts#458]
The OpenTelemtry Operator helm chart doesn't use `"opentelemetry-operator.labels"` and `"opentelemetry-operator.selectorLabels"` apart from: webhook, service, service monitor, and prometheus rule. See for example [deployment.yaml#L4](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/templates/deployment.yaml#L4) and [deployment.yaml#L12](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/templates/deployment.yaml#L12). 

This behaviour is different to the collector and causes an issue because we are not able to just grab `helm.sh/chart` from the labels and detect drift between the environments easily. 

I feel like this is a relatively easy fix and would be happy to raise a PR.

**Comment by edwintye** [comment]
Ah, I was complaining about this at work to @LinuxAd about this and it seems like both of us decided that an upstream contribution will be faster 🤣

**Comment by TylerHelmuth** [comment]
@edwintye @LinuxAd thanks for contributing. Can you choose one of the PRs to centralize on and close the duplicate?

**Comment by LinuxAd** [comment]
Sure, I'll close mine now.
