### ISSUE TITLE
Add "schedulingRules" to jaeger

### ISSUE THREAD

**Issue by tglanz** [open-telemetry/opentelemetry-helm-charts#504]
In the demo chart - I'd like to have the ability to specify node affinities for Jaeger's pod which from my understanding, is currently not support.

Is it reasonable to add the existing schedulingRules to the [values schema](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/values.schema.json) and update [Jaeger template](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/templates/jaeger.yaml) accordingly?

Thanks.

**Comment by TylerHelmuth** [comment]
I agree that the jaeger deployment should be able to set scheduling rules as well.  @tglanz would you like to work on this?

**Comment by tglanz** [comment]
great, on it

**Comment by tglanz** [comment]
@TylerHelmuth opened pr #505
