### ISSUE TITLE
Add Helm chart to deploy OpenTelemetry Operator in an Kubernetes cluster

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-helm-charts#51]
*Is your feature request related to a problem? Please describe.*

The Collector is deployed today using the OpenTelemetry Operator. We would like to add an OpenTelemetry Operator Helm chart to give the users another choice to deploy the Operator. With this Helm chart, users will have the flexibility to tune the configurations passed into the Operator and manage the OpenTelemetry Operator efficiently.

*Describe the solution you'd like*

We are designing and building an Helm chart with the OpenTelemetry Operator being the package content. We plan to add this Helm chart to the existing OpenTelemetry Helm repository (https://github.com/open-telemetry/opentelemetry-helm-charts).

*Describe alternatives you've considered*

We reviewed the Prometheus Helm chart (https://github.com/prometheus-community/helm-charts) and it did not meet our needs.

*Additional context*

We are using the existing OpenTelemetry Collector Helm chart (https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector).

cc: @Saber-W @Raul9595 @alexperez52

**Comment by alolita** [comment]
Hi @tigrannajaryan @dmitryax can you assign this issue to @Saber-W 

Thanks!

**Comment by Saber-W** [comment]
The design doc of the OpenTelemetry Operator Helm chart is [here](https://docs.google.com/document/d/1JwQqFnHlhtr0XT3NYrGF3yK-5xIzRagGpXbw_u0wfGo/edit?usp=sharing).

Thank you!

**Comment by dmitryax** [comment]
The design doc looks good to me. Thanks for providing it.

**Comment by Saber-W** [comment]
Hi @dmitryax, thank you!
