### ISSUE TITLE
OOM for frontendproxy

### ISSUE THREAD

**Issue by zhuoyuan-liu** [open-telemetry/opentelemetry-helm-charts#511]
Hi there,

The latest helm chart set memory limits 20Mi to frontendproxy, which results in OOMKilled.

After increasing the memory limit, everything works fine.

**Comment by TylerHelmuth** [comment]
@zhuoyuan-liu where did you deploy the chart?  I have be able to use the defaults as expected.

**Comment by zhuoyuan-liu** [comment]
Thanks for answering. 

I tried to deploy the latest chart and everything is okay. I got this error with chart version 0.12.0 in AKS.

**Comment by TylerHelmuth** [comment]
@zhuoyuan-liu Great! If things are working as expected now please close this issue.
