### ISSUE TITLE
hostmetrics preset filesystem config

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-helm-charts#537]
So the current situation is:
- I added filesystems in PR -> https://github.com/open-telemetry/opentelemetry-helm-charts/commit/d065b6b40ce1fde7d0245efadefe74066c572d5d
- This tries to scrape metrics for all the fielsystems
- This typically causes errors in the Collector.

Examples:
```
2022-12-02T14:22:24.979Z        error   scraperhelper/scrapercontroller.go:214  Error scraping metrics  {"kind": "receiver", "name": "hostmetrics", "pipeline": "metrics", "error": "failed to read usage at /boot: no such file or directory; failed to read usage at /var/lib/kubelet/pods/75ea3ea3-f784-423d-9635-25a9ef668858/volumes/kubernetes.io~local-volume-mongo: no such file or directory", "scraper": "filesystem"}
```

```
/var/lib/kubelet/plugins/kubernetes.io/csi/ebs.csi.aws.com/ebdcc357ad138b3ee228b233fcc7fe4fbe0393c49dc8dc420a248d8b1e41668e/globalmount: no such file or directory; failed to read usage at /var/lib/kubelet/pods/6b6567dc-6a31-4d07-b3ab-2e7dff54bfc1/volumes/kubernetes.io~csi/pvc-594d005e-632e-4b21-a099-c852a72e522a/mount: no such file or directory", "scraper": "filesystem"}
```

I know folks also have similiar errors scraping  `/snap`, `/var/lib/kubelet/..`

Good discussions:
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/533#discussion_r1036149185
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/496

What do we do?

Options:
- Deprecate & revert filesystem scraper pr (No more out of space metrics/alerts :cry: ) 
- FIgure out some default include list / exclude list that works?

**Comment by TylerHelmuth** [comment]
@povilasv is the list proposed in https://github.com/open-telemetry/opentelemetry-helm-charts/pull/496 a good list?

```yaml
exclude_mount_points:
  mount_points:
    - /snap/*
    - /boot/*
    - /var/lib/kubelet/pods/*
    - /var/lib/kubelet/plugins/*
  match_type: regexp
```

**Comment by dmitryax** [comment]
I agree that we should update the default config of the filesystem scraper to whatever makes the most sense for containers and don't throw any warnings. 

Also we should adopt recently added feature https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver#collecting-host-metrics-from-inside-a-container-linux-only and remove the gopsutil env variables
