### ISSUE TITLE
Improve otel demo's metric monitoring.

### ISSUE THREAD

**Issue by wph95** [open-telemetry/opentelemetry-helm-charts#571]
# Motivation

The current demo chart will install prometheus and collect metric for some components.
However, it does not collect k8s metric.

I've done some local test and not found that a simple modification of values.yaml collect k8s metric.

# PLAN

So I want to solve the problem with the following goal.
1. the user only needs `prometheus.kube-state-metrics: enable` to let prometheus collect k8s metric (currently we have custom scrape_configs, so just enable configuration can't collect data)

2. the user can collect container information in a simple way (via cadvisor)

**Comment by Saki042** [comment]
@TylerHelmuth , Can I more info about the issue and is it open to work?

**Comment by TylerHelmuth** [comment]
We tend to let the chart follow features driven by the demo sig, closing as Not Planned for now
