### ISSUE TITLE
Helm scheme doesn't support service annotations for frontendProxy

### ISSUE THREAD

**Issue by andrew-lozoya** [open-telemetry/opentelemetry-helm-charts#609]
When configuring the frontendProxy component, It is beneficial to configure the frontendProxy component to support additional annotations for managed services like AWS Load Balancer Controller, such as Network Load Balancer (NLB) with instance or IP targets through a Kubernetes service of type LoadBalancer with relevant annotations. However the scheme does not support this today, and static IPs can not be assigned. 

i.e.
```
service.beta.kubernetes.io/aws-load-balancer-type
service.beta.kubernetes.io/aws-load-balancer-eip-allocations
service.beta.kubernetes.io/aws-load-balancer-subnet
```

**Comment by puckpuck** [comment]
yeah, we should add support for service annotations.

I hate to introduce a `serviceAnnotations` parameter at the components level. I would prefer to deprecate the existing `serviceType` and `servicePort` parameters in favor of folding everything into a `service` object instead. This would match what other charts do as well.

We have to make a change like this backward compatible, but I'm going to want to think about a deprecation policy to minimize how long we carry the tech debt.
