### ISSUE TITLE
[operator] Use fullname for naming objects instead of name

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-helm-charts#612]
> I think thats probably not best either.  I think in almost all resource naming cases we should be using `fullname`, but it looks like the chart is using `name`.  Since switching to `fullname` is a part of bigger issue, we can handle it in its own PR. I'm ok with using `name` for this PR.

_Originally posted by @TylerHelmuth in https://github.com/open-telemetry/opentelemetry-helm-charts/pull/611#discussion_r1082889862_

**Comment by sfenman** [comment]
May I open a PR for this?

**Comment by Allex1** [comment]
sure. Thanks
