### ISSUE TITLE
Consistent way of defining labels/annotations

### ISSUE THREAD

**Issue by Allex1** [open-telemetry/opentelemetry-helm-charts#628]
Currently extra labels/annotations are being injected in different ways across resource types. We should try and keep them consistent while allowing for the `tpl` [function](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function) to inject helm variables trough values.yaml.

**Comment by yamagai** [comment]
Hello @Allex1, I'm new here and would like to contribute!

The goal is to align the way to specify extra anntation/labels in each resource with the following, right?
```
    {{- range $key, $value := .Values.<resource>.<extraLabels/Annotations> }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
```

**Comment by Allex1** [comment]
@yamagai yes, go for it. Thanks
