### ISSUE TITLE
Permission management for prometheus receivers

### ISSUE THREAD

**Issue by paologallinaharbur** [open-telemetry/opentelemetry-helm-charts#63]
I am currently testing the prometheus receiver.
The chart creates a service account with no specific permission, therefore I faced the classical `Failed to watch *v1.Service`

Which is the recommended way to set up RBAC for the service account this chart creates?
Should this chart provide something similar to [what prometheus chart](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/server/clusterrole.yaml)does or due to the number of receivers is not feasible?

**Comment by dmitryax** [comment]
Because prometheus receiver is not part of the default config. Several optional components like k8s processor or prometheus receiver require additional RBAC. 

We need to add an option to specify rbac in the chart
