### ISSUE TITLE
[demo] Update chart to use service account object

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-helm-charts#643]
The demo chart allows specifying a service account name, but not creating a service account.  That chart should be updated to use a service account section similar to the opentelemetry-collector chart and it should also allow creating a service account.

**Comment by danweller18** [comment]
It works for me. Example:
in `values.yaml`
```
serviceAccount:
  create: true
  name: "otel-collector-contrib-sa"
```

helm cmd
`helm upgrade -i otel-collector-contrib open-telemetry/opentelemetry-collector --version 0.48.0 -f values.yaml -n observability --create-namespace`

output after running helm cmd
```
kubectl get serviceaccounts -A                                
NAMESPACE         NAME                                      SECRETS   AGE
default           default                                   0         120d
...
observability     default                                   0         2m19s
observability     otel-collector-contrib-sa                 0         2m19s
```

**Comment by TylerHelmuth** [comment]
@danweller18 sorry my description was wrong.  The collector chart service account object is correct, its the demo chart that isnt.
