### ISSUE TITLE
[demo] helm install error: function "mustFromJson" not defined

### ISSUE THREAD

**Issue by gerbil** [open-telemetry/opentelemetry-helm-charts#664]
Documentation: https://opentelemetry.io/docs/demo/kubernetes-deployment/

Step: To install the chart with the release name my-otel-demo, run the following command:
> helm install my-otel-demo open-telemetry/opentelemetry-demo

Try with 
> helm version
version.BuildInfo{Version:"v3.4.0-rc.1"

> helm install my-otel-demo open-telemetry/opentelemetry-demo                                          
**Error: parse error at (opentelemetry-demo/templates/_pod.tpl:11): function "mustFromJson" not defined**

src:
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/36d6b236a92745b82858fd2e703cd5669ad23cfa/charts/opentelemetry-demo/templates/_pod.tpl

**Comment by TylerHelmuth** [comment]
@gerbil the demo [prerequisites](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-demo#prerequisites) require using helm 3.9+.  Can you try with a 3.9+ version of helm?
