### ISSUE TITLE
[demo] Add Security Context for all demo components

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-helm-charts#665]
Some secured environments, such as OpenShift, require pods to run under a defined security context. This is done for some demo components but not all.

**Comment by realtimetodie** [comment]
I am working with Openshift and I have many problems deploying this chart. It does not work out of the box.

A work in progress howto guide is here

https://gist.github.com/realtimetodie/c69563c6b9398f22e6621083f6027dba

**Comment by puckpuck** [comment]
@realtimetodie What about SecurityContext for the components? Do you need to specify that as well?

**Comment by realtimetodie** [comment]
In OpenShift, it is enough to define an empty security context

```
spec:
  securityContext: {}
```

This means, the current setup with the various `runAsUser: 43` configurations causes errors in OpenShift.

**Comment by puckpuck** [comment]
This isn't needed, in fact the opposite may be required for proper OpenShift support
