### ISSUE TITLE
Kubernetes Events preset

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-helm-charts#669]
Opening an issue for discussion, we could use [k8sobjectsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sobjectsreceiver) to watch Kubernetes Events and add a preset similiar to Kubernetes logs preset.

One caveat the receiver [k8sobjectsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sobjectsreceiver)  is alpha stability.

Thoughts?

Reference: https://github.com/open-telemetry/opentelemetry-helm-charts/issues/381

cc @nicolastakashi

**Comment by nicolastakashi** [comment]
Just a small note!
The `k8seventsreceiver` we're planning to add as a preset as described on the issue as reference is still an ALPHA receiver, maybe should be something we must highlight to the user that may have breaking changes in the future.

**Comment by TylerHelmuth** [comment]
I support adding a preset for `k8sobjectreceiver` with a clear warning, both in the values.yaml and in `NOTES.txt` that the component is alpha.

**Comment by nicolastakashi** [comment]
@povilasv and @TylerHelmuth I'm going to prepare a PR for this.

**Comment by nicolastakashi** [comment]
@povilasv we can close this 😄
