### ISSUE TITLE
[demo] Do we need `observability` section?

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-helm-charts#682]
Why do we need a separate section to disable/enable observability components? Maybe better to add `enabled` option to each observability component itself? It'll be in line with how regular components can disabled.

**Comment by TylerHelmuth** [comment]
Using the `opentelemetry-collector`, `jaeger`, `prometheus`, `grafana` now makes sense to me.  We have to check and make sure those charts allow adding fields tho.  We had to explicitly add `enabled` as a valid field to the collector chart for this use case.
