### ISSUE TITLE
Latest version in helm repo is 0.2.0

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-helm-charts#72]
```
helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
helm repo update
helm search open-telemetry
```

Latest version shown is 0.2.0

Release workflow seems to not be detecting chart changes for some reason

https://github.com/open-telemetry/opentelemetry-helm-charts/runs/3490399927?check_suite_focus=true

```
Looking up latest tag...
Discovering changed charts since 'opentelemetry-operator-0.3.1'...
Nothing to do. No chart changes detected.
```

**Comment by indrekj** [comment]
Noticed that as well. Maybe related to https://github.com/helm/chart-releaser-action/issues/71

**Comment by indrekj** [comment]
Still a problem,

https://github.com/open-telemetry/opentelemetry-helm-charts/runs/3580447145

Now failed with:
```
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.        
remote: error: Required status check "EasyCLA" is expected.        
To https://github.com/open-telemetry/opentelemetry-helm-charts
 ! [remote rejected] HEAD -> gh-pages (protected branch hook declined)
error: failed to push some refs to 'https://github.com/open-telemetry/opentelemetry-helm-charts'
Error: exit status 1
```

**Comment by anuraaga** [comment]
We have permission to disable the branch permission for code that doesn't add copyright, which covers basically every release workflow so this should be ok to disable too.

The trick we found in the Java repo is first deleting `*/**` rule added by the easycla bot, adding a rule for the release branch, then re-adding the `*/**` bot. Attempting to add before deleting that doesn't work. /cc @trask

CNCF acting too much like a big brother is still a concern even after that workaround ;)
