### ISSUE TITLE
[opentelemetry-collector] Add Support for NetworkPolicy

### ISSUE THREAD

**Issue by fernferret** [open-telemetry/opentelemetry-helm-charts#722]
I'd like to propose adding [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) support to the helm chart.

There are a few different use cases I can see:

* In `DaemonSet` mode, restrict the ability to access the collector to only cluster nodes or specific namespaces.
* In `Deployment`/`StatefulSet` mode, restrict collection to specific namespaces.

This would help a lot in a multi-tenant environment. The primary motivation of having the `NetworkPolicy` in this chart is to keep the object installed/updated along side the collector.

I'm willing to write up a PR with this if the team thinks this would be useful/accepted!

**Comment by TylerHelmuth** [comment]
As long as it's optional and configurable sounds like a good idea to me.
