### ISSUE TITLE
Support installing to user-defined namespace

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-helm-charts#73]
I create my own namespace, for example `monitoring`, and pass it to the helm command when applying the chart, but this chart seems to have a requirement on its name as I still get the error `namespaces "opentelemetry-operator-system" not found`. It should be possible to install into any namespace, respecting the helm namespace argument

**Comment by anuraaga** [comment]
FWIW, I don't know if I've seen another chart that automatically creates a namespace. I think it's idiomatic in helm to expect the user to create a namespace as appropriate.

**Comment by pragmaticivan** [comment]
@anuraaga could you share how you are installing your config? I got it working on a specified namespace I created already.

```
helm upgrade ent-opentelemetry-collector open-telemetry/opentelemetry-collector \
  --install \
  --kube-context "my-kube-context" \
  --repository-config "${K8S_FOLDER}/helm/chart_repos.yaml" \
  --values "${K8S_FOLDER}/staging/helm/otel-collector/values.yaml" \
  --namespace "mynamespace" \
  --version "0.5.10"
```
