### ISSUE TITLE
[collector] Enable daemonset service for local node networking

### ISSUE THREAD

**Issue by danweller18** [open-telemetry/opentelemetry-helm-charts#749]
Allow for a daemonset to be configured to have a service with local internal traffic policy.

Since Kubernetes v1.26 you can enable `internalTrafficPolicy: Local` to route service traffic to the same node. This same concept of sending application records to the same node otel collector, was suggested [here](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/524#issuecomment-1328084428) in a previous issue. Now there is a kubernetes supported way to do this without having to know the node_ip up front. 

Reference: https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/
```
spec:
  internalTrafficPolicy: Local
```

Use case:
Application sending OTLP logs to otel collector on the same node. The application has no way to know ahead of time what the static node ip will be and thats why a kubernetes service with a local traffic policy is the ideal solution.

**Comment by puckpuck** [comment]
Using a Service on a Daemonset is a Kubernetes anti-pattern that should be avoided.

It's recommended you use this when you set up the `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable for your application pods that are sending logs, when the collector is deployed as a Daemonset:

```
- name: NODE_IP
   valueFrom:
     fieldRef:
       fieldPath: status.hostIP
- name: OTEL_EXPORTER_OTLP_ENDPOINT
   value: http://$(NODE_IP):4317
```

**Comment by danweller18** [comment]
Could you share any documentation discussing a service on a daemonset as a kubernetes an anti-pattern so I can learn more? I am unable to find anything related to your statement. The kuberntes [docs](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#communicating-with-daemon-pods) even specify one possible way to communicate with a daemonset pod is to use a service.

Yeah our application is not setup currently to grab the NODE_IP from the host node, but that seems like a good possible solution.

**Comment by TylerHelmuth** [comment]
Pinging @danweller18 and @achetronic as you've both expressed interest in this recently.

Enough users have requested this capability (service for a daemonset) so we're willing to allow it.  We have these requirements:

1. A Service should always be created for a Deployment and a Statefulset
2. A Service is never created for a Daemonset by default, it must be explicitly enabled via some config option.  All the existing Daemonset mode defaults should be untouched and any changes to allow a service need to be made without a breaking change.
4. When creating a Service for a Daemonset we need to be able to configure `internalTrafficPolicy: Local`.
    - side note, our charts support the same versions of k8s that the k8s community is support which I believe is currently 1.24.  @danweller18 do you know if `internalTrafficPolicy: Local` is usable in 1.24 and 1.25?
5. When creating a Service for a Daemonset without `internalTrafficPolicy: Local` we need to be able to warn that this is not a best practice and is not recommended.  It should also be clear in our README and values.yaml.

To start, we're most interested in how the config will look like in the values.yaml.  Let's work on that and then once we agree someone can start implementing and submit a PR.

**Comment by achetronic** [comment]
> Pinging @danweller18 and @achetronic as you've both expressed interest in this recently.
> 
> Enough users have requested this capability (service for a daemonset) so we're willing to allow it. We have these requirements:
> 
>     1. A Service should always be created for a Deployment and a Statefulset
> 
>     2. A Service is never created for a Daemonset by default, it must be explicitly enabled via some config option.  All the existing Daemonset mode defaults should be untouched and any changes to allow a service need to be made without a breaking change.
> 
>     3. When creating a Service for a Daemonset we need to be able to configure `internalTrafficPolicy: Local`.
>        
>        * side note, our charts support the same versions of k8s that the k8s community is support which I believe is currently 1.24.  @danweller18 do you know if `internalTrafficPolicy: Local` is usable in 1.24 and 1.25?
> 
>     4. When creating a Service for a Daemonset without `internalTrafficPolicy: Local` we need to be able to warn that this is not a best practice and is not recommended.  It should also be clear in our README and values.yaml.
> 
> 
> To start, we're most interested in how the config will look like in the values.yaml. Let's work on that and then once we agree someone can start implementing and submit a PR.

Hello there,

About points 3 and 4, this feature graduated to Beta on 1.24 and to GA on 1.26, [according to this docs](https://kubernetes.io/blog/2022/12/30/advancements-in-kubernetes-traffic-engineering/#optimizing-internal-node-local-traffic) so it is supported

Do you want me to implement it on the chart and make a purpose? :)

**Comment by danweller18** [comment]
> Pinging @danweller18 and @achetronic as you've both expressed interest in this recently.
> 
> Enough users have requested this capability (service for a daemonset) so we're willing to allow it. We have these requirements:
> 
> 1. A Service should always be created for a Deployment and a Statefulset
> 2. A Service is never created for a Daemonset by default, it must be explicitly enabled via some config option.  All the existing Daemonset mode defaults should be untouched and any changes to allow a service need to be made without a breaking change.
> 3. When creating a Service for a Daemonset we need to be able to configure `internalTrafficPolicy: Local`.
>    
>    * side note, our charts support the same versions of k8s that the k8s community is support which I believe is currently 1.24.  @danweller18 do you know if `internalTrafficPolicy: Local` is usable in 1.24 and 1.25?
> 4. When creating a Service for a Daemonset without `internalTrafficPolicy: Local` we need to be able to warn that this is not a best practice and is not recommended.  It should also be clear in our README and values.yaml.
> 
> To start, we're most interested in how the config will look like in the values.yaml. Let's work on that and then once we agree someone can start implementing and submit a PR.

Thanks I appreciate the follow up to consider adding this feature. 

Yes I do know that `internalTrafficPolicy: Local` works in 1.24 because I have enabled and verified `internalTrafficPolicy: Local` works in version 1.24 myself.

For daemonset services I suggest that you only support creating a service with `internalTrafficPolicy: Local`. That would help discourage using a normal network routing service- for daemonsets.

I was thinking that you add the local option [here](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L337):
```
service:
  type: ClusterIP
  # type: LoadBalancer
  # loadBalancerIP: 1.2.3.4
  # loadBalancerSourceRanges: []
  annotations: {}
  internalTrafficPolicy: Local
```

The caveat is I am unsure what kubernetes does if you attempt to use `internalTrafficPolicy: Local` with deployment type of `deployment`

**Comment by TylerHelmuth** [comment]
@achetronic I like being able to set `internalTrafficPolicy` explicitly to Cluster to handle the (in my opinion incorrect, but never the less frequently asked for) situation when users when to send traffic from one node to a daemonset instance on another.

This configuration does not handle how to enable a service for a Daemonset.  I do not think we want to add an `enabled` field into the `service` configuration since we don't want to be able to disable it for `deployment` or `statefulset`.  I think we need a new root-level field or a field in the service configuration that is named daemonset-specific and can only be true if mode=daemonset.

**Comment by achetronic** [comment]
> @achetronic I like being able to set `internalTrafficPolicy` explicitly to Cluster to handle the (in my opinion incorrect, but never the less frequently asked for) situation when users want to send traffic from one node to a daemonset instance on another.
> 
> This configuration does not handle how to enable a service for a Daemonset. I do not think we want to add an `enabled` field into the `service` configuration since we don't want to be able to disable it for `deployment` or `statefulset`. I think we need a new root-level field or a field in the service configuration that is named daemonset-specific and can only be true if mode=daemonset.

mmmm what about creating the flag on the root `serviceOnDaemonset: true`?? This will allow us to document the change with a header of comments

**Comment by achetronic** [comment]
Hi again @TylerHelmuth and @danweller18 
[In this PR](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/755) I have implemented everything we talked about in this thread
 
Could you please review the changes?

**Comment by achetronic** [comment]
Time to close this issue as far as the code was already merged 🙏🏼

**Comment by dima-sh-papaya** [comment]
> Using a Service on a Daemonset is a Kubernetes anti-pattern that should be avoided.
> 
> It's recommended you use this when you set up the `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable for your application pods that are sending logs, when the collector is deployed as a Daemonset:
> 
> ```
> - name: NODE_IP
>    valueFrom:
>      fieldRef:
>        fieldPath: status.hostIP
> - name: OTEL_EXPORTER_OTLP_ENDPOINT
>    value: http://$(NODE_IP):4317
> ```

this doesn't allow for automatic fallback to another pod in the cluster in case the local agent went belly up - is it still the recommended way to run the collector? or is there a better approach nowadays? I'm setting up the otel collector for the first time, with a requirement to have both local traffic 'priority' (to avoid cross-AZ in EKS) and a fallback in case local collector is not available. One thing comes to mind is to run two daemon-sets or an additional deployment in the cluster, as a fallback for any single failed daemonset pods, but how to instruct the app from the pod to use one or the other as a fallback is a question 🤔
