### ISSUE TITLE
Collector Helm chart: File collector never collects any logs

### ISSUE THREAD

**Issue by agronholm** [open-telemetry/opentelemetry-helm-charts#754]
The default configuration, when log collection is enabled, never collects any logs because the [include/exclude paths](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/_config.tpl#L182-L187) are wrong. The host file system (where the logs are) is mounted at `/hostfs`, so these paths also need to start with that, otherwise nothing is ever collected.

**Comment by agronholm** [comment]
I see now what the issue is. The `logsCollection.enabled: true` preset is what adds the correct mount for `/var/log/pods`. I could not use the preset because I had JSON logs that needed to be parsed, and there is no way to add your own configuration on top of the default `filelog` configuration, so only way to accomplish that was to disable the preset and manually configure the `filelog` receiver by copying its configuration from the preset to my `values.yaml` and adding the appropriate operators. That volume mount was the missing piece then.

**Comment by TylerHelmuth** [comment]
@agronholm you should be able to add/update the filelogreceiver configuration created by the preset, you only can't remove content.  Any configuration you add to `.Values.config` will be applied on top of the preset configuration.  You would still have to add the volume mount yourself.
