### ISSUE TITLE
Add optional ingress for otel collector

### ISSUE THREAD

**Issue by pragmaticivan** [open-telemetry/opentelemetry-helm-charts#76]
It might be useful for exposing the collector for SPA apps (react) and perhaps adding another way of redirecting requests to a oauth proxy.

**Comment by dmitryax** [comment]
Hi @secustor @pragmaticivan , can you please provide more evidence why the ingress should be part of the collector helm chart?

The general idea is to keep this helm chart thin and provide only necessary resources to support OpenTelemetry collector in k8s environment.

I don't believe that ingress has to be part of this chart. I think it should be deployed with nginx-ingress helm chart separately.

**Comment by secustor** [comment]
I'm not sure, if we talk about the same.    

What I'm referencing is a simple Ingress object  like in my PR, which cannot be deployed using the nginx-ingress helm chart. Usually these are packaged with the corresponding applications. e.g. [Loki](https://github.com/grafana/helm-charts/blob/main/charts/loki/templates/ingress.yaml) from Grafana and [Jaeger](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/query-ing.yaml)

Regarding the addition of an ingress controller to this helm chart. I'm of your opinion, this should not included in this helm chart. 


My use case is to ingest data from external applications which are instrumentalized with Opentelemetry.      
To secure the endpoint an API gateway is used. 
Most API gateway implementation, I'm aware of, utilize ingress objects as basis for there configurations.

**Comment by pragmaticivan** [comment]
Same as above. This ticket was intended for the Ingress resource, not the operator.
