### ISSUE TITLE
Use ${env:ENV} style syntax when getting environment variables

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-helm-charts#761]
The OpenTelemetry Collector supports both the legacy `${ENV}` syntax as well as the new `${env:ENV}` syntax (enabled by default since v0.62.0, see open-telemetry/opentelemetry-collector@b15179e4da112b8ce2b56c6cd336072f7307c87a, fully working for the use case of this Helm chart since v0.71.0, see open-telemetry/opentelemetry-collector@202c03010605012f00b01c45ff90b1a0afd46c01). The latter is preferred and we have updated examples in the OpenTelemetry Collector repository to use it (see open-telemetry/opentelemetry-collector-contrib/issues/17299).

The Helm chart uses the legacy syntax since #603, see https://github.com/open-telemetry/opentelemetry-helm-charts/blob/7252934f33a67697fd04558da3ce750fc70f25eb/charts/opentelemetry-collector/values.yaml#L82-L96

We should use the new `${env:ENV}` style syntax here instead. Note that this would break users of the Collector < v0.71.0 (not sure how this is handled in the Helm chart, but we may want to wait a bit).

**Comment by JaredTan95** [comment]
I'd like to update this, pls assign it to me :-P
