### ISSUE TITLE
POD still trying to pull the Image from default location even though values for operator overridden for private registry  

### ISSUE THREAD

**Issue by sreejesh-radhakrishnan-db** [open-telemetry/opentelemetry-helm-charts#785]
I use private registry hence I overridden the below value in operator install for automatic instrumentation values image 

https://github.com/open-telemetry/opentelemetry-helm-charts/blob/4fa9fb7be5afb929454494956e8a146358c24be0/charts/opentelemetry-operator/values.yaml#L39-L51

I can see kinds : instrument have correctly showing the Image path.
 instrumentation.opentelemetry.io/default-auto-instrumentation-java-image: artifactory.sdlc.ctl.gcp.db.com/dkr-all/dkr-ghr/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.25.1

but when I annotated the POD and whist its starting its still looking for ghcr.io/<> the default one? any idea what I am missing?

Error on POD-   Back-off pulling image "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.24.0"

**Comment by sreejesh-radhakrishnan-db** [comment]
# Default values for opentelemetry-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

## Provide a name in place of opentelemetry-operator.
##
nameOverride: ""

## Reference one or more secrets to be used when pulling images from authenticated repositories.
imagePullSecrets: [ { name: regcred } ]

## Pod Disruption Budget configuration
##
pdb:
  ## Enable/disable a Pod Disruption Budget creation
  ##
  create: false
  ## Minimum number/percentage of pods that should remain scheduled
  ##
  minAvailable: 1
  ## Maximum number/percentage of pods that may be made unavailable
  ##
  maxUnavailable: ""

## Provide OpenTelemetry Operator manager container image and resources.
##
manager:
  image:
    repository: artifactory.sdlc.ctl.gcp.db.com/dkr-all/dkr-ghr/open-telemetry/opentelemetry-operator/opentelemetry-operator
    tag: v0.75.0
  collectorImage:
    repository: artifactory.sdlc.ctl.gcp.db.com/dkr-all/dkr-io/otel/opentelemetry-collector-contrib
    tag: 0.75.0
  targetAllocatorImage:
    repository: ""
    tag: ""
  autoInstrumentationImage:
    java:
      repository: "artifactory.sdlc.ctl.gcp.db.com/dkr-all/dkr-ghr/open-telemetry/opentelemetry-operator/autoinstrumentation-java"
      tag: "1.25.1"
    nodejs:
      repository: "artifactory.sdlc.ctl.gcp.db.com/dkr-all/dkr-ghr/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs"
      tag: "0.38.0"
    #python:
    #  repository: ""
    #  tag: ""
    #dotnet:
    #  repository: ""
    #  tag: ""
  ports:
    metricsPort: 8080
    webhookPort: 15017
    #webhookPort: 9443
    healthzPort: 8081
  resources:
    limits:
      cpu: 300m
      memory: 2280Mi
    requests:
      cpu: 100m
      memory: 64Mi
  ## Adds additional environment variables
  ## e.g ENV_VAR: env_value
  env:
    ENABLE_WEBHOOKS: "true"

  # -- Create the manager ServiceAccount
  serviceAccount:
    create: true
    annotations: {}
    # name: nameOverride

  ## Enable ServiceMonitor for Prometheus metrics scrape
  serviceMonitor:
    enabled: false
    # additional labels on the ServiceMonitor
    extraLabels: {}
    # add annotations on the ServiceMonitor
    annotations: {}
    metricsEndpoints:
    - port: metrics

  podAnnotations: {}
  podLabels: {}

  prometheusRule:
    enabled: false
    groups: []
    # Create default rules for monitoring the manager
    defaultRules:
      enabled: false
    # additional labels on the PrometheusRule
    extraLabels: {}
    # add annotations on the PrometheusRule
    annotations: {}


  ## List of additional cli arguments to configure the manager
  ## for example: --labels, etc.
  extraArgs: []

  ## Enable leader election mechanism for protecting against split brain if multiple operator pods/replicas are started.
  ## See more at https://docs.openshift.com/container-platform/4.10/operators/operator_sdk/osdk-leader-election.html
  leaderElection:
    enabled: true

  # Enable vertical pod autoscaler support for the manager
  verticalPodAutoscaler:
    enabled: false
    # List of resources that the vertical pod autoscaler can control. Defaults to cpu and memory
    controlledResources: []

    # Define the max allowed resources for the pod
    maxAllowed: {}
    # cpu: 200m
    # memory: 100Mi
    # Define the min allowed resources for the pod
    minAllowed: {}
    # cpu: 200m
    # memory: 100Mi

    updatePolicy:
      # Specifies whether recommended updates are applied when a Pod is started and whether recommended updates
      # are applied during the life of a Pod. Possible values are "Off", "Initial", "Recreate", and "Auto".
      updateMode: Auto
      # Minimal number of replicas which need to be alive for Updater to attempt pod eviction.
      # Only positive values are allowed. The default is 2.
      minReplicas: 2
  # Enable manager pod automatically rolling
  rolling: false

## Provide OpenTelemetry Operator kube-rbac-proxy container image.
##
kubeRBACProxy:
  enabled: true
  image:
    repository: artifactory.sdlc.ctl.gcp.db.com/dkr-all/dkr-gcr/kubebuilder/kube-rbac-proxy
    tag: v0.14.0
  ports:
    proxyPort: 8443
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi

  ## List of additional cli arguments to configure the kube-rbac-proxy
  ## for example: --tls-cipher-suites, --tls-min-version, etc.
  extraArgs: []

## Admission webhooks make sure only requests with correctly formatted rules will get into the Operator.
## They also enable the sidecar injection for OpenTelemetryCollector and Instrumentation CR's
admissionWebhooks:
  create: true
  failurePolicy: Fail
  secretName: ""

  ## Adds a prefix to the mutating webook name.
  ## This can be used to order this mutating webhook with all your cluster's mutating webhooks.
  namePrefix: ""

  ## Customize webhook timeout duration
  timeoutSeconds: 10

  ## Provide selectors for your objects
  namespaceSelector: {}
  objectSelector: {}

  ## Provide the issuer kind and name to do the cert auth job.
  ## By default, OpenTelemetry Operator will use self-signer issuer.
  certManager:
    # false means helm will create self-signd cert and secret for you.
    enabled: true
    issuerRef: {}
      # kind:
      # name:
    # Annotations for the cert and issuer if cert-manager is enabled.
    certificateAnnotations: {}
    issuerAnnotations: {}

## Create the provided Roles and RoleBindings
##
role:
  create: true

## Create the provided ClusterRoles and ClusterRoleBindings
##
clusterRole:
  create: true

affinity: {}
tolerations: []
nodeSelector: {}
topologySpreadConstraints: []
hostNetwork: false

# Allows for pod scheduler prioritisation
priorityClassName: ""

## SecurityContext holds pod-level security attributes and common container settings.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532

testFramework:
  image:
    repository: dkr-all/dkr-io/busybox
    tag: 1.35.0

**Comment by sreejesh-radhakrishnan-db** [comment]
Sorry for horrible formatting  I cannot upload file due to restrictions

**Comment by sreejesh-radhakrishnan-db** [comment]
Just to add I am applyig the below manifest for Instrumentation 

https://opentelemetry.io/docs/k8s-operator/automatic/#java

I can see in GKE objectrbowser this is having the right Image  link  



apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation

> metadata:

>    annotations:

   

>  instrumentation.opentelemetry.io/default-auto-instrumentation-dotnet-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:0.6.0

 

>    instrumentation.opentelemetry.io/default-auto-instrumentation-java-image: artifactory.sdlc.ctl.gcp.db.com/dkr-all/dkr-ghr/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.25.1

 

>    instrumentation.opentelemetry.io/default-auto-instrumentation-nodejs-image: artifactory.sdlc.ctl.gcp.db.com/dkr-all/dkr-ghr/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.38.0

>    instrumentation.opentelemetry.io/default-auto-instrumentation-python-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.38b0
    

> kubectl.kubernetes.io/last-applied-configuration: |

      {"apiVersion":"opentelemetry.io/v1alpha1","kind":"Instrumentation","metadata":{"annotations":{},"name":"care-optl-instrumentation","namespace":"cnap"},"spec":{"exporter":{"endpoint":"http://care-optl-collector:4317"},"java":{"image":"artifactory.sdlc.ctl.gcp.db.com/dkr-all/dkr-ghr/open-telemetry/opentelemetry-operator/autoinstrumentation-java"},"propagators":["tracecontext","baggage"],"sampler":{"argument":"1","type":"parentbased_traceidratio"}}}

**Comment by sreejesh-radhakrishnan-db** [comment]
After the above step I annotated the POD which is my JAVA application like this 

  kubectl patch deployment  buildpack-java -p '{"spec": {"template":{"metadata":{"annotations":{"instrumentation.opentelemetry.io/inject-java":"true"}}}} }'  

and there the annotation is correct and I can see on YAML its refering to ghrc link and not artifactory. 


apiVersion: v1
kind: Pod

> metadata:

  

> annotations:

   

> 

>  instrumentation.opentelemetry.io/inject-java: "true"

......


 - image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.24.0
    imageID: ""
    lastState: {}
    name: opentelemetry-auto-instrumentation
    ready: false
    restartCount: 0
    state:
      waiting:
        message: Back-off pulling image "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.24.0"
        reason: ImagePullBackOff

**Comment by TylerHelmuth** [comment]
@sreejesh-radhakrishnan-db can you confirm that you definitely only have 1 instrumentation resource created in the namespace of the app?

**Comment by sreejesh-radhakrishnan-db** [comment]
Yes - I have checked that 
![image](https://github.com/open-telemetry/opentelemetry-helm-charts/assets/79570391/c806b22e-102e-4e95-a0b1-7ae90663a775)

**Comment by sreejesh-radhakrishnan-db** [comment]
just to check what is the source of image repo for autoinstrumentaion?   when I annotate a pod? is it taken from Instrumentation ?  I can try to delete and recreate and see what happens?

**Comment by sreejesh-radhakrishnan-db** [comment]
I removed and added annotation and it seems to work and picking up the correct image repo.  hence clsoing the issue.  thanks @TylerHelmuth  for your time.
