### ISSUE TITLE
Possible to link optl collector to cloud trace - GCP

### ISSUE THREAD

**Issue by sreejesh-radhakrishnan-db** [open-telemetry/opentelemetry-helm-charts#786]
Hi
Sorry first of all, this is not an issue,  rather a help or direction I need to take. 

I have now installed , operator, collector, auto-instrument for java and annotated the pod.

I can see on Collector LOG Trace and SPAN getting generated.   

My Q sorry a very nave one.  how will I visualise this?  we are in GKE and Google does provide GOOGLE CLOUD TRACE> 

Is there any way I can expose the date from collector to CLOUD TRACE at all?

**Comment by TylerHelmuth** [comment]
Which tool you use to visualize telemetry is up to you.  You can view the exporters of the collector here: https://github.com/open-telemetry/opentelemetry-collector-contrib.  I am not familiar with Google Cloud Trace.

I would suggest asking this question in the CNCF slack in one of the otel channels or in the collector contrib discussion board.  A link to the CNCF slack can be found here: https://opentelemetry.io/community/.

I am going to close this issue as it isn't related to the helm charts.
