### ISSUE TITLE
error calling eq: incompatible types for comparison

### ISSUE THREAD

**Issue by sharadregoti** [open-telemetry/opentelemetry-helm-charts#878]
Release "opentelemetry-collector" does not exist. Installing it now.
Error: template: opentelemetry-collector/templates/service.yaml:38:28: executing "opentelemetry-collector/templates/service.yaml" at <include "opentelemetry-collector.serviceInternalTrafficPolicy" .>: error calling include: template: opentelemetry-collector/templates/_helpers.tpl:154:44: executing "opentelemetry-collector.serviceInternalTrafficPolicy" at <eq .Values.service.enabled true>: error calling eq: incompatible types for comparison

Getting this error when installing helm chart
helm upgrade -i opentelemetry-collector open-telemetry/opentelemetry-collector

**Comment by TylerHelmuth** [comment]
@sharadregoti what version of helm are you using? I have seen this error before with helm versions below 3.9

**Comment by sharadregoti** [comment]
Thanks it worked. I was using 3.7, upgrading to the latest version solved the issue
