### ISSUE TITLE
Removing operator leaves CRD; all operations on CRD return errors or hang

### ISSUE THREAD

**Issue by beggers** [open-telemetry/opentelemetry-helm-charts#909]
Hello!

I'm trying to instrument a relatively fresh EKS cluster with OTel. I'm using ArgoCD to deploy to my cluster with manifests specified as Helm charts in a private Github repo.

I set up `cert-manager` just fine by adding it to my `dependencies` clause in `Chart.yaml`. Easy.

Then I deployed the `opentelemetry-operator` by adding it to my `Chart.yaml`:

```
  - name: opentelemetry-operator
    version: ^0.1.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
```

And adding some config to `values.yaml`:

```
opentelemetry-operator:
  admissionWebhooks:
    certManager:
      create: true
```

My cluster wasn't happy -- the `cert-manager-cainjector` pod was crashlooping for a while and is now in state `ERROR` (I think this is unrelated to OTel). So I removed `opentelemetry-operator` from my `Chart.yaml` and now my cluster is pretty broken:

```
beggers % kubectl describe opentelemetrycollectors.opentelemetry.io
Error from server (InternalError): Internal error occurred: error resolving resource

beggers % kubectl api-resources | grep opentelemetry
opentelemetrycollectors           otelcol,otelcols        opentelemetry.io/v1alpha1                 true         OpenTelemetryCollector

beggers % kubectl get otelcol -A
Error from server (InternalError): Internal error occurred: error resolving resource

beggers % kubectl describe otelcol
Error from server (InternalError): Internal error occurred: error resolving resource
```

Trying to delete the CRD gives me the following output then hangs forever:
```
beggers % kubectl delete crd opentelemetrycollectors.opentelemetry.io
customresourcedefinition.apiextensions.k8s.io "opentelemetrycollectors.opentelemetry.io" deleted
```

What can I do to clean up from this experiment? Thanks very much in advance.

**Comment by beggers** [comment]
Hey @povilasv , thanks for the suggestion. I deleted both the `cert-manager` and `opentelemetry-operator` `mutatingwebhookconfigurations` but the errors persist when I try to describe the otel stuff. Do you have any advice for how to proceed from here?

I can just delete and recreate my cluster since we don't have production traffic yet but I'd strongly prefer to learn how to fix this the right way :D]

**Comment by TylerHelmuth** [comment]
@povilasv is correct.  Since this is a helm issue and not a chart issue I am going to close this.  Please ping us if the advice does not work.

**Comment by beggers** [comment]
It doesn't work -- when I try to delete the CRD the operation hangs forever and the CRD remains as originally reported. I'm happy to report this somewhere else if there's a better place for it.
