### ISSUE TITLE
[collector] `useGOMEMLIMIT: true` makes otel col startup faild

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-helm-charts#912]
I tested with `useGOMEMLIMIT: true` after https://github.com/open-telemetry/opentelemetry-helm-charts/pull/900 merged But I got the following errors and otel col could not startup: 
```bash
GOMEMLIMIT=1024Mi
fatal error: malformed GOMEMLIMIT; see `go doc runtime/debug.SetMemoryLimit`

runtime stack:
runtime.throw({0x7ca4cb5?, 0xa?})
	runtime/panic.go:1077 +0x5c fp=0x7ffc561f55c8 sp=0x7ffc561f5598 pc=0x43ba5c
```

so, I change `GOMEMLIMIT=1024Mi` into `GOMEMLIMIT=1024MiB` according [go runtime docs](https://pkg.go.dev/runtime) and otel-col startup success.

**Comment by TylerHelmuth** [comment]
This was called out here, and I thought I included that suggestion in the suggestion batch, but it looks like I missed it: https://github.com/open-telemetry/opentelemetry-helm-charts/pull/900#discussion_r1348078633. Are you able to submit a PR to fix this?
