### ISSUE TITLE
[collector] Add support for KEDA autoscaling

### ISSUE THREAD

**Issue by zehenrique** [open-telemetry/opentelemetry-helm-charts#914]
I would like to propose KEDA support to the OpenTelemetry Collector helm chart so that the Collector is able to autoscale based on metrics other than CPU and Memory.

https://github.com/kedacore/keda
"KEDA allows for fine-grained autoscaling for event-driven Kubernetes workloads."

Similarly to HPA, KEDA would apply to `Kind: Deployment` only.

Use Case:
We have a Collector with a KafkaReceiver receiving logs from a Kafka topic. We would like to be able to scale automatically based on metrics such as Kafka lag, for example.

**Comment by TylerHelmuth** [comment]
I am not familiar with this project, but _in general_, we don't like when installing the helm chart depends on other Operators being installed.  We currently have 2 exceptions: the operator chart's default install expects the cert-manager, and the collector chart allows installing some objects that depend on the Prometheus operator.

Is using the Collector chart with keda possible today if you managed the keda objects outside the collector chart?

**Comment by zehenrique** [comment]
I totally understand that. Only suggested it because Keda is becoming the de facto standard for Kubernetes-based Event Driven Autoscaling.

Yes, it is possible to use outside the collector chart. Will be more complicated to manage and maintain but it is possible.
