### ISSUE TITLE
[Security recommendation] Enabling Allstar for monitoring organization-wide policies 

### ISSUE THREAD

**Issue by EjiroLaurelD** [open-telemetry/opentelemetry-helm-charts#931]
[Allstar](https://github.com/ossf/allstar) was proposed as a way to achieve consistency across the repositories in the org with regards to security policy. 
It is a policy-based security tool that can help us to enforce security requirements and best practices across our organization. It can be used to enable and configure a variety of security tools and settings, such as CodeQL, static code analysis tools, and repository security settings.

I am proposing that we enable Allstar for this repository. Allstar will automatically configure a variety of security tools and settings for this repository. This will help us to improve the security of this repository and our organization's software as a whole.

Please let me know if you have any questions or concerns.

Parent issue: https://github.com/open-telemetry/sig-security/issues/21
cc @codeboten @jpkrohling

**Comment by jpkrohling** [comment]
I'm not sure this is the right repository for this issue. Shouldn't we be able to handle this all from the Security SIG?

**Comment by EjiroLaurelD** [comment]
@jpkrohling Yes, the Security SIG can handle enabling Allstar for all the repositories in the organization.
I may have misunderstood the instruction on the parent issue requesting to open issues on appropriate repositories. My apologies. Am I to create this issue on the security sig with the proposed steps?

**Comment by jpkrohling** [comment]
The issue is for the SIG Security determine whether our tentative recommendations are already implemented by all repositories, and to check whether allstar can be used to cover those recommendations.
