### ISSUE TITLE
[opentelemetry-operator] Webhook configuration rules are missing the scope field

### ISSUE THREAD

**Issue by b3ndill** [open-telemetry/opentelemetry-helm-charts#939]
Hello!

We're running a few GKE clusters and recently installed the `opentelemetry-collector` using your Helm chart (version 0.34.1).
After installing we've started receiving notifications (called insights) in the GKE cluster console like this:

> This cluster has an admission webhook installed that is intercepting system critical requests in the last 24 hours. Intercepting these requests can impact availability of the GKE Control Plane.

The documentation Google provides points to the `MutatingWebhookConfiguration` and advises you to set up a `namespaceSelector` to omit the `kube-system` and `kube-node-lease` namespaces as well as restricting the rule scope to the filtered resources.
Using the Helm chart, I can set the `namespaceSelector` easily in the chart values file and it works fine but I can't set the rule scope using the Helm chart and since the default value for `scope` is `'*'`, I am forced to edit the rule manually to resolve the notification in the console.

The resources referenced in the admission-webhook templates are `pod`, `instrumentations` and `opentelemetrycollectors`. Since both the `instrumentations` and `opentelemetrycollectors` custom resource definitions are using the `Namespaced` scope and pods are of course also a namespaced resource, I would recommend either just adding a `scope: 'Namespaced'` line to the rules or making `scope` a configurable value.

You can find the relevant documentation reference from Google here: https://cloud.google.com/kubernetes-engine/docs/how-to/optimize-webhooks#unsafe-webhooks

**Comment by TylerHelmuth** [comment]
@b3ndill would you like to submit a fix for this?

**Comment by b3ndill** [comment]
> @b3ndill would you like to submit a fix for this?

I can, although I haven't done anything like this before. I'll read over the guidelines and propose a fix before the weekend.
