### ISSUE TITLE
k8sattributes processor not collecting metadata on AKS

### ISSUE THREAD

**Issue by libormezl** [open-telemetry/opentelemetry-helm-charts#950]
## Description
I am attempting to enhance logs from the OLTP receiver with metadata using the k8sattributes processor. Unfortunately, I cannot observe any metadata in App Insights or even in the logging exporter. There are no errors visible in the logging exporter either.

I am deploying through the Terraform Helm provider in daemonset mode.

Within the logging exporter, I can see k8s.pod.ip: Str(10.244.8.1), indicating that there is an IP available to map the resource's metadata.

## Component(s)
processor/k8sattributes

## Helm version
0.73.0

## Expected Result
to see default metadata described [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md)
- k8s.namespace.name
- k8s.pod.name
- k8s.pod.uid
- k8s.pod.start_time
- k8s.deployment.name
- k8s.node.name

## Configuration
    mode: daemonset
    
    presets:
      kubernetesAttributes:
        enabled: true
    
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: ${env:MY_POD_IP}:4317
            http:
              endpoint: ${env:MY_POD_IP}:4318
    
      exporters:
        azuremonitor:
          instrumentation_key: "key" 
          spaneventsenabled: true
    
        logging:
          loglevel: debug
    
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [k8sattributes]
            exporters: [azuremonitor, logging]
    
          logs:
            receivers: [otlp]
            processors: [k8sattributes]
            exporters: [azuremonitor]
    
          metrics:
            receivers: [otlp]
            processors: [k8sattributes]
            exporters: [azuremonitor]

**Comment by TylerHelmuth** [comment]
@libormezl is it possible the incoming telemetry is coming from an IP address that is different than the pod's IP address? By default the processor uses the incoming connection to map the data to the pod.  If the processor is not reporting errors and isn't associating data my guess is that the IP address are not matching. 

If the incoming telemetry already has k8s.pod.name set on the resource the processor can use that value to match to the pod metadata instead.

**Comment by libormezl** [comment]
@TylerHelmuth, you are right. The every incoming k8s.pod.ip I have found in logs is xxx.xxx.xxx.1 (same for one node, different per multiple nodes) and does not belong to any existing pod in the node.

Thank you for you hint, I am going to investigate this behavior.

**Comment by libormezl** [comment]
I have resolved this issue by referencing the daemonset using service with _internalTrafficPolicy: Local_ and not using _status.hostIP_
