### ISSUE TITLE
Cluster Role Binding subjects namespace incorrect when overriding namespace

### ISSUE THREAD

**Issue by nittendev** [open-telemetry/opentelemetry-helm-charts#953]
Hi.

I've observed an issue when deploying the collector chart with an overriden namespace.
The clusterrolebinding gets the wrong subject namespace and incorrect access as a result.

I believe the issue is located here:
`charts/opentelemetry-collector/templates/clusterrolebinding.yaml`

Line 21:
`namespace: {{ .Release.Namespace }}`

I belive? it should be something like:
`namespace: {{ template "opentelemetry-collector.namespace" . }}`

**Comment by etiennep** [comment]
I'd like to work on this.

**Comment by TylerHelmuth** [comment]
@etiennep thank you, but there is already a PR submitted: https://github.com/open-telemetry/opentelemetry-helm-charts/pull/960
