### ISSUE TITLE
CrashLoopBackOff in cartservice when fs.inotify.max_user_instances is set to a relatively low number

### ISSUE THREAD

**Issue by aknot242** [open-telemetry/opentelemetry-helm-charts#961]
When deploying the opentelemetry-demo using the Helm chart, the cart service has a watcher responsible for reloading when files are changed. In host systems where the `fs.inotify.max_user_instances` is set to a relatively low value, the container will crash loop with a log message similar to the following:

```
Unhandled exception. System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file
```

**Comment by aknot242** [comment]
Potential fix:

Since containers deployed via Helm are typically not for development purposes, there may not be a need to watch for changing files at all. According to this, the watching can be disabled altogether via an environment variable:

```
DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
```

**Comment by puckpuck** [comment]
Please create this issue on the demo repo. We should fix this within the demo itself, and not with how it is deployed using Helm

**Comment by aknot242** [comment]
As requested, created the issue in the demo repo: https://github.com/open-telemetry/opentelemetry-demo/issues/1310
