### ISSUE TITLE
kubeletMetrics preset not collecting volume metrics 

### ISSUE THREAD

**Issue by mpostument** [open-telemetry/opentelemetry-helm-charts#969]
Hello, kubeletMetrics do not have configured metrics groups. And because it using default value only metrics from containers, pods and nodes is collected. But metrics from volumes are missing. 

Lets maybe add volumes to metrics group or make it configurable?

**Comment by mpostument** [comment]
Yes, i did override. If you think there is no reason to enable all metric_groups we can close this one

**Comment by TylerHelmuth** [comment]
@mpostument we'll stick to the kubeletstats receiver defaults (container, pod, node) for now.  Thank you!
